### ISSUE TITLE
U2F adoption: Schools Payment System

### ISSUE THREAD

**Issue by slisznia** [2factorauth/twofactorauth#1092]
Hi, I'd like to add a service that uses U2F to your list - https://pushcoin.com

School administrators login and authenticate via U2F.

**Comment by Carlgo11** [comment]
Hi Slawomir!

Thank you for suggesting this site.
While we'd love to add all the sites people suggest we simply don't have the time to do so.
twofactorauth is a volunteer based project and we all do this on our spare time.

Maybe you could add this in a Pull Request? If not then maybe you could ask one of the developers of pushcoin to do so?
You can use [this tutorial](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_TFA_SITE) to add the site to our list.

Also, I can't seem to log in to https://www.pushcoin.com/ when I don't have an American IP address. Maybe you should fix that? IP addresses aren't that accurate and people often hide their IP address behind proxies which might show up as they're in another country or from "Anonymous proxy".

**Comment by slisznia** [comment]
We understand you're busy. Unfortunately the site is for U.S. visitors only
due to privacy over student data. The message you saw was intentional.

If this isn't a suitable entry for your list then we can pass. Otherwise
I'll be happy to send a git pull request.

**Comment by Carlgo11** [comment]
Hi again,
yes but as I said IP addresses can't be treated like normal addresses. I have an American IP address and I'm not American. Many people in America use IP addresses from some European countries since they have better privacy laws and I'm guessing people on vacation in another country should be able to use your system?

Rather than block ips outside of the U.S. I recommend just asking the visitor if they're American or not.
After all, if someone really wants to get around your blocking it's fairly easy to do.
I've seen 9-year-olds use proxies and VPN tunnels.

Anyways, I'm fairly sure we do accept region specific sites since many banks listed on our site is region specific (although they don't block traffic).

**Comment by RichJeanes** [comment]
@slisznia Do you have a link to any public documentation of this security feature? Is it only for school administrators or do parent accounts have TFA as well? You appear to accept online payments from parents (and therefore handling/storing payment info).
I would like to get a pull request put together so that we can get this issue closed and PushCoin on the list.

**Comment by slisznia** [comment]
We currently only offer U2F to school admins. Parents will either be
offered rolling numbers or U2F, we aren't certain which yet. The problem
with U2F is that it's not mobile friendly and lots of our parents use
smartphones.

Slawomir Lisznianski
Software Architect, PushCoin

**Comment by RichJeanes** [comment]
Do you have a link to any public documentation for having/setting up TFA on an account?

**Comment by slisznia** [comment]
http://knowhow.pushcoin.com/using-security-key-for-2-step-verification/

Slawomir Lisznianski
Software Architect, PushCoin

**Comment by RichJeanes** [comment]
Thank you. I'll tag you when the PR is submitted so that you may review it.

Also, Chrome does not require any plug-ins to use U2F devices, so perhaps that line and its links are unnecessary.
As for TFA for parents, U2F does support communication methods other than USB, such as Bluetooth and NFC. Perhaps for parents, consider ~~U2F over NFC (though of course this is limited by phone hardware having NFC and using a YubiKey Neo), or~~ supporting SMS based OTP as many online services provide.

Edit: Yubico has said that "The FIDO Alliance will present extensions to the U2F specification that support [NFC and Bluetooth]" [here](https://www.yubico.com/2015/01/fido-u2f-ecosystem-coming-alive/). I don't know if those are live yet. They also point out PushCoin's support, if you didn't know about that. Hooray for recognition!

**Comment by slisznia** [comment]
Yes, we will soon remove the use of the extension on our site and just
use the builtin support.

Slawomir Lisznianski
Software Architect, PushCoin
