### ISSUE TITLE
Entertainment Category?

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#1117]
Does this need to exist? Do any of these sites actually meet the [Site Criteria](../blob/master/CONTRIBUTING.md#site-criteria)? YouTube only has TFA because it's a Google site.

I suppose you could make the argument that access could affect personal image or profits with sites where you can create content (eg being a streamer on Twitch or content creator on Vimeo), but Netflix and Hulu?

On a separate point, isn't Grooveshark dead?

**Comment by mxxcon** [comment]
Regarding grooveshark, #1101.
While some of those sites might not fit those specific criteria, I think their profile is high enough to be a common target of attacks?

**Comment by Carlgo11** [comment]
yup.
Just imagine what someone could do with a YouTube celebrity's account...

When it comes to Netflix and Hulu, a lot of TFA requests on Twitter are actually pointed towards Netflix.
I'm guessing people really want TFA on their Netflix accounts so it would be rather bad to remove it from the list.

**Comment by RichJeanes** [comment]
As I say, I can see the argument for content creation sites.

If you say that we should include other entertainment services like Netflix and Hulu because people want TFA on those accounts, that means that we are ignoring our own criteria. Just because people want it doesn't mean it's necessary or provides any benefit. I believe that if the sites are going to stay, then we need to either find actual justification for them within our criteria we have set forth or we need to modify our criteria in some way so that they can be justified. Otherwise they should be removed.

I would just rather not have to deal with people claiming us unfair for turning down their suggested site for not fitting criteria when we have ones that (IMO) don't meet criteria just because they have large user bases. I just want to be following our own rules, ya know?

That said, really looking over them, I don't know that I understand what is included under "Personal Info" with criteria 1. Amazon is listed as an example. Is it because Amazon has your address and phone number? If so, wouldn't that be any online merchant? That sounds like a can of worms waiting to be opened if you ask me.

**Comment by Carlgo11** [comment]
@jdavis I think we need your opinion here.

**Comment by plecavalier** [comment]
I for one would argue any and all sites are relevant merely on the basis
that weak link to someones info is a weak point and can be used for an
attack.

EDIT: (signature & quote removed by @Carlgo11)

**Comment by mxxcon** [comment]
@plecavalier Then we would be listing every single site on the internet that has a login. This is not something we are going to do.
Yes, we want as many sites as possible to have 2fa, but not every single one has to be listed here. That's why we created that criteria.

(also please don't include your email signatures in replies. It creates unnecessary noise)

**Comment by jdavis** [comment]
I feel that content creation sites make a lot of sense to be on the list. So this includes Soundcloud, Twitch, Vimeo and others. Because there are a lot of DJ's that use Soundcloud and producers that use Vimeo. Their "Image" (first criteria) is pretty dang important.

As for content consuming sites, like Netflix, Hulu, Spotify (since most musicians go through labels anyways), etc. are a bit more on the iffy side. I'd say no but some people disagree so I feel that if someone makes the PR, it gets the `looks-good` label, and it gets merged, then who am I to say otherwise?

**Comment by Carlgo11** [comment]
so @jdavis, should we close this ticket then?
