### ISSUE TITLE
Toopher acquired by Salesforce

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#1173]
I can't tell what the status of the product will be post-integration by the letter on their [website](https://www.toopher.com/)...

**Comment by mxxcon** [comment]
> Even though we will no longer sell our current product, our commitment to your security remains steadfast (as does our love for breakfast tacos).
> Stay tuned for more exciting news!

So I think it's worth removing them since new users can't sign up and existing users don't really need this site.

**Comment by smholloway** [comment]
Salesforce Authenticator should replace Toopher. But before I update the providers... how do y'all feel about nuking the provider page altogether? I created it thinking it would be a valuable addition to the site, but it's been a pain in my ass ever since--and I imagine others feel the same way. The page is a confusing time suck that draws spammy PRs from marketers who don't bother to read the manual. I vote to return the site to the simple list of sites with and without two factor authentication.

**Comment by mxxcon** [comment]
Seth, congrats on acquisition, hopefully it's not acquikill.
Yes, I do wonder how useful providers page is... It is indeed mostly abused as a promotional page.

**Comment by jamcat22** [comment]
Agree with @mxxcon on this one. It seems to have turned into a marketing tool.

**Comment by jdavis** [comment]
I'm in favor of nuking it.

It's pretty surprising how many emails I get from someone about that page. I think the marketers/managers just go to the repo, see that I own it and blast out an email. It has decreased over time but none the less...

I think it was a good idea for sure at the start but the site can exist without it now =]

**Comment by smholloway** [comment]
Good, it sounds like we're all in agreement! I've made the PR (PR #1177).
