### ISSUE TITLE
Different means of contacting the sites not supporting TFA

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1212]
Right now we only support Twitter to ask companies to support TFA. Maybe we could add Facebook & Email as well since some sites don't use Twitter or don't listen to tweets mentioning them.

**Comment by mxxcon** [comment]
Is there a way to create ready-to-use facebook post?

**Comment by Carlgo11** [comment]
Nope. But we could link them to the FB page and then they could tell them themselves.

**Comment by dullroar** [comment]
I would add to this that I actually think using social media to do this is wrong, wrong, wrong from a security point of view. Think about it - you are basically telling the world (unless these things are sent as private messages, but it doesn't look that way) that you have an account at a site that doesn't support 2FA. So if the bad guys can figure out who you are from your Twitter handle (usually not hard) they're already have another interesting piece of info about you - that you bank at Poorly Protected Bank & Trust, which opens up things to social engineering as well as just trying to figure out your account and password.

**Comment by RichJeanes** [comment]
That's a bit of a fallacy. You run that same risk every time you hand your debit or credit card to a waiter/waitress/cashier. More so, in fact, because they could then skim your card and get more than just your name and bank.

**Comment by dullroar** [comment]
No, that argument is a red herring. Because I am handing it off to one person at a time, not the whole world with a searchable hash tag. The point is to not needlessly increase the attack surface, as opposed to getting bogged down in the whole, "Well, you're exposed over here anyway" argument. Because if that's the case, why use 2FA at all, if we're f----ed already?

**Comment by dullroar** [comment]
To avoid getting into an argument, I would rather that notifications to orgs that don't support 2FA be made by private IM, not public tweet.

**Comment by RichJeanes** [comment]
If you are concerned about that, then feel free to message them privately. While using a public medium may increase your attack surface (though to what degree is arguable), the point of making the statement publicly is to draw attention to the issue and spread awareness. A lot more people use Twitter than may necessarily know about twofactorauth.org which means the message can reach a grater audience and get more people contacting the service about providing TFA. How anyone wishes to display their support, whether publicly or privately, is completely up to them. We don't force anyone to use Twitter, though, yes, we do encourage it through including the link to try to spread awareness.

**Comment by mxxcon** [comment]
@dullroar Part of it is intentional public shaming. To make a public statement that everybody can see that such-and-such doesn't support 2FA.
Just because you talk about some site's 2FA on Twitter does not automatically mean you actually use it. There is nothing in the messaging that says you use a given service. 
If this is a concern for you, you should not use your real name on Twitter, you should not use the same usernames on all services and if possible other services should not have your real name either.

**Comment by RichJeanes** [comment]
Closing since email and Facebook contact has been implemented.
