### ISSUE TITLE
QNAP (NAS)   (official build 4.2 and later)

### ISSUE THREAD

**Issue by vincentcox** [2factorauth/twofactorauth#1365]
I see that Synology is also on the list, but Qnap is missing. (If you have no idea what I am talking about: Qnap and Synology are 2 big NAS brands. Their software offers backups, file sharing, logging, web server,... all on a NAS in your home. In other words, it contains a lot of important data, and 2FA is a must for these things).
The latest build (4.2.0) allows 2 factor authentication via the google app.
Source: https://www.qnap.com/qts/4.2/en/security.php
Why I didn't make a pull request: I am worried about breaking the build (which is rule 1 in the contributing file). But I hope someone else is able to do this, so other users visiting the website can see that their QNAP device offers 2FA.
<img width="939" alt="2015-10-12_13-25-06" src="https://cloud.githubusercontent.com/assets/9286611/10426873/af95388c-70e4-11e5-8dbc-09c723b9344c.png">

**Comment by RichJeanes** [comment]
You're welcome to try your hand at a PR; that can only break something if it gets merged in with problems. Since all PRs are reviewed by at least two collaborators, that shouldn't happen. Feel free! Just read through [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).

**Comment by jamcat22** [comment]
We should probably use https://www.qnap.com/i/useng/tutorial/con_show.php?op=showone&cid=151 for the doc link. Feel free to make a PR!
