### ISSUE TITLE
Have a page for each service and requesters.

### ISSUE THREAD

**Issue by will** [2factorauth/twofactorauth#139]
Twitter search only goes back so far, It'd be powerful to have a page that was the twitter avatars of everyone who pressed the button that link to their tweet.

**Comment by jdavis** [comment]
That's a really cool idea (and powerful, like you said).

Since we're using Jekyll/GitHub Pages, it would be a bit harder to do. We should just decide if it would be easy to do as a cronjob type thing and grab Tweets every hour or so, or if real time is a better option.

I'm not familiar with the Twitter API so I don't know if we'd run into any limitations. That would have to be looked into.

**Comment by jdavis** [comment]
While I think this would be great, I'm closing for now. Maybe in the future we could look into this. :smile:

**Comment by will** [comment]
We shipped 2fa at heroku, so I don't need this myself anymore ;)

**Comment by jdavis** [comment]
Is it out of beta yet?

**Comment by will** [comment]
No still beta, but public now instead of private beta

On Jun 16, 2014, at 8:01 PM, Josh Davis notifications@github.com wrote:

Is it out of beta yet?
