### ISSUE TITLE
Please add Zurich Cantonal Bank (ZKB)

### ISSUE THREAD

**Issue by huggi** [2factorauth/twofactorauth#1407]
``` websites:
  - name: Zurich Cantonal Bank (ZKB)
    url: https://www.zkb.ch/
    img:  https://upload.wikimedia.org/wikipedia/commons/6/60/Z%C3%BCrcher_Kantonalbank_logo.svg
    tfa: Yes
    sms: Yes
    email: Yes
    phone: Yes
    software: Yes
    hardware: Yes
    doc: https://www.zkb.ch/de/gs/lp/ebanking.html
```

Reference: https://en.wikipedia.org/wiki/Zurich_Cantonal_Bank

**Comment by Carlgo11** [comment]
@huggi you're creating issues and not PRs. Read the Wiki or google if you don't know how to create a PR.
Please don't add more issues like this. You clearly know how our layout is set up (except that images should be added to `_img/<section>` and 32x32 pixes) so try and create a PR instead.

**Comment by huggi** [comment]
@Carlgo11 sorry, I'm not really expirienced like you think, what's a PR? But yes, I will not add any further issues/banks. No worries have a nice weekend.

**Comment by Carlgo11** [comment]
No worries.
I'll write some instructions for you. There might be some typos though because I'm writing on my phone since I'm on my lunch break.

I'm assuming you're in Windows.
1. Download GitHub for windows.
2. Create a fork of this project.
3. Download your fork via GitHub for Windows.
4. Go to your GitHub folder (probably in `C:\Users\<name>\Documents\Github\Twofactorauth\`)
5. edit `_data\banking.yml` using your text editor of choice. (Add your contribution there)
6. Add a logo to `_img\banking\<bank name>` (The same name as you set `img:` to in banking.yml)
The logo should be a .png image and exactly 32x32 pixels. Also, compress it if it's larger than ~2kb
7. Mark your changes on GitHub for Windows and create a "commit".
8. Upload your commit ("sync" or "push" button)
9. follow the instructions on https://help.github.com/articles/creating-a-pull-request to make the PR.

**Comment by Carlgo11** [comment]
@huggi to go back to this issue.
I can't find any relevant pages on zkb about two factor authentication.
Could you please link me one?

**Comment by Carlgo11** [comment]
Hello again @huggi!
I still haven't found anything on zkb mentioning two factor authentication.
Would appreciate if you could send me a link :wink:

**Comment by stephengroat** [comment]
Does this help? https://www.zkb.ch/de/pr/pk/efinance/ebanking/login-verfahren.html

**Comment by Carlgo11** [comment]
Yes it does. Do you mind updating #1878 with that doc link?

**Comment by stephengroat** [comment]
done
