### ISSUE TITLE
Why is the documentation refereing to: TFA.org which is not reachable?

### ISSUE THREAD

**Issue by huggi** [2factorauth/twofactorauth#1408]
Thanks!

**Comment by mxxcon** [comment]
I don't understand your question.

**Comment by RichJeanes** [comment]
Are you asking about things like the title on [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)? That is just a shorthand so that it isn't as long (hence why it is not hyperlinked). Anywhere the site is actually linked to should be [TwoFactorAuth.org](https://twofactorauth.org).
