### ISSUE TITLE
Add new column for push notification type 2FA

### ISSUE THREAD

**Issue by SecuritySimon** [2factorauth/twofactorauth#1421]
Many vendors now have the ability to apply 2FA auth via push notification type responses on devices, for example.

https://www.authy.com/product/options/#onetouch
https://www.duosecurity.com/product/user-experience/authentication
https://www.telesign.com/products/push-verify/

twofactorauth.org should therefore allow us to see which websites are using these modern methods of 2FA.

**Comment by mxxcon** [comment]
It is a property of either `software` or `sms` type 2fa systems.

**Comment by SecuritySimon** [comment]
Push notification doesn't use SMS at all, it leverages either the Apple push notification mechanism (APNS) or the Google push notification system (Cloud Communication). So it's not a property of the SMS type of 2FA.

You are correct in that it is a software implementation of 2FA, however twofactorauth.org has a column for "Software Token" which is not the same as push notification based 2FA.

It is worth differentiating between token based software implementations and push notification. Because they deliver totally different user experiences and also provide a different level of security. TOTP via software apps leverage shared secrets, where as push notification implementations use asynchronous cryptography with a private key generated on the device and public keys communicated to the 2FA vendors service.

The user experience for push is also totally different to Software Token based. The end user receives a notification, typically with a dialog that prompts for an Accept or Deny response. The users response to the notification results in real time communication with the calling application. I.e. you click on login on the website, your phone beeps, you accept the notification and the website automatically logs you in. In contrast, Software Token based approaches simply generate a token which the end user has to retype into the website to continue login. The token is also the only piece of information available to the end user, while push notification usually carries an interface to the user that contains a lot more information about the current login. This informs the end user to make the decision to Accept or Deny.

The following video shows an example of SMS, software token and push notification all in one demo.
https://www.youtube.com/watch?v=gqMz9XQ2pSs

So due to the difference in the types of client software 2FA implementations, Software Token and Software Push need to be identified differently, and therefore I suggest a new column for push based solutions.

**Comment by smholloway** [comment]
I think a short-term fix is to rename the column headers to `Software` and `Hardware` to match the abstraction we created to accommodate the variety of authentication systems available. There's a lot of debate about the meaning of a "token"--it's easier to classify something that requires an app (software) or a dedicated physical device (hardware).

At the heart of it, I think @SecuritySimon is suggesting that we classify 2fa based on the interaction method. I think we do a pretty good job of that already, but perhaps we could change to columns like `input a token` (received via SMS, email, voice, or read from an app or fob) or `push a button` (touch-activated hardware tokens and push-based mobile two-factor). With two columns we could maintain the same level of information by adding icons for the various delivery methods. For example, a site that supports RFC6238 one-time passwords would have a software and hardware icon in the `input a token` column; a site using Duo would have an icon for phone, sms, and app in the `input a token` column as well as a software icon in the `push a button` column.

**Comment by RichJeanes** [comment]
I think you're hitting more on an issue of language and wording. The column is titled "Software Token" mostly because "Software Implementation" is long and ugly looking on the table. You also notice how it _doesn't_ say "TOTP", because that column isn't just for TOTP. 

Also, you say "The end user receives a notification, _typically_ with a dialog that prompts for an Accept or Deny response." (emphasis mine)
Steam Guard for Android pushes a notification when a login attempt is made, but it contains the code that has to be typed in. Should that go in Push or Software?

Besides, push notifications are still software dependent. You must have a specific app installed and configured to work with your account to function. The main benefit of SMS is that it has no such requirement. (It even works on non-smartphones!) And with most SMS based authentication systems, it is very fast and reliable these days. I can't remember the last time a code took more than 3-4 seconds to get to my phone - much faster than opening an app - and it appears on my lock screen or in my notifications - just like a push message.

My point is, I feel like the end user experience is not different enough to warrant it's own column. Our goal is to inform the everyday user/consumer. They don't care about how it works behind the scenes. To a degree, I could almost argue that the SMS and Software columns should be merged! But the main difference is that the "Software Token" mark means that it uses some protocol for delivering your authentication factor proof (whether that's a code the user types in or a button they press) that requires the user to install a specific or separate piece of software to do so.

**Comment by RichJeanes** [comment]
@smholloway That's a good thought, but I feel that's a bit of a step in the wrong direction and could lead to information overload. The main advantage we have with the separate columns and check marks is that it is easy to look at and know _what_ you're looking at. Once you start throwing in several icons, you need a key/legend, it has to be displayed all over the page otherwise you have to keep scrolling to look at it (tool tips don't do much for mobile users, which is already an area of issue). Then what about hardware fobs without a button (some U2F dongles)? Is the code generating fob generic or vendor/site specific? There's a lot of information that _could_ go on the site, but there is reason that it isn't. It's the same slippery slope that we've been trying to avoid in a different guise (lots of icons vs. lots of columns).

I think the main reason we have a "Hardware" column isn't so much about how what you have to do to authenticate, but rather indicating that you have to have a separate piece of hardware that you have to always have access to to log in (which is what differentiates it from "Software", since this typically applies to smartphone apps (though, yes, there are desktop applications for code generation, but they aren't very common)).

**Comment by SecuritySimon** [comment]
@RichJeanes said...

"Steam Guard for Android pushes a notification when a login attempt is made, but it contains the code that has to be typed in. Should that go in Push or Software?"

Ah ha, that is a good point. I think what i'm trying to differentiate here is that software token mechanisms (even when a push notification is used to alert the user to the token) are different in user experience to a push notification that results in a prompt to the user that when responded to, sends a realtime communication to the calling application. i.e. the user doesn't need to retype a token into the app. This real time communication from the phone back to the calling service is very different to token based solutions. To compare...

Software Token: End user must get a token (via SMS, voice, hardware or software app) that the user must retype into the target service/application.

Real Time 2FA (for want of a better phrase): End user is notified in software (phone, tablet or could be a Chrome/Windows/Mac desktop notification) of a pending 2FA action. User responds to some UI (Usually presenting an Accept or Deny) and the response results in an immediate response from the calling application.

I believe, and therefore the reason behind my requesting this issue, is that the two behaviors above are important to communicate to end users. Entering a token into an application is an old method, while the real time 2FA communication (again, not really happy with this naming) is a better experience for users. Real time 2FA also can be more effectively applied to in-application authorization steps and is better positioned to replace the entire username/password as the auth. The best example here is Yahoo Account Key. https://help.yahoo.com/kb/SLN25781.html. This is clearly a different approach than entering in a token (no matter where that token comes from) and I would suggest it's a better user experience. Capital One also have something called SwiftID which replaces the use of security questions as a second factor of authentication. http://techcrunch.com/2015/10/23/capital-one-launches-swiftid-a-way-to-bypass-security-questions-with-just-a-swipe/

I also think that what vendors should be doing is offering a range of capabilities. As @RichJeanes states, SMS requires no app to be installed, works on non smart phones, and the delivery of SMS today is fast and reliable. However being able to embed a real time software based 2FA SDK into an existing app (aka Captial One and Yahoo) is a better user experience for users that may already have the vendors mobile app installed.

I'm not sure on the right way to display this data however. Do you have "Software Token" and "Software Real Time"? 

Complicating matters further is FIDO. I use a hardware FIDO compliant device to authenticate to to my GMail in Chrome (FIDO not supported in IE, Firefox or Safari). Now this is hardware, but there is no token for me to retype... How would this fall into the current categorization?

**Comment by mxxcon** [comment]
Simon, the reason for breakdown into the current categories is that we want to communicate to users what would be required from them to enable 2fa.
Some users might not want to carry or pay for a hardware dongle. Other users might not have an SMS capable phone or voice plan...
I feel that these factors are more important than a difference between entering a code vs taping on "allow/reject".
I'm not against finding a simple way to display your suggestion, but I don't think we should completely switch to it.

**Comment by jamcat22** [comment]
I'm going to close this issue, as it really fits into already existing issues, like #521 and #1368.

**Comment by RoyiAvital** [comment]
Yahoo uses the 2FA only on new devices and not for each login.

I would not call it 2FA.

**Comment by jamcat22** [comment]
Hello @RoyiAvital,

Thanks for your input! This closed thread has not been active since November of 2015 and is unrelated to whether or not a website should be classified as having 2FA. We currently classify websites as having 2FA if they require an additional factor during the login process, whether or not it's required at every login from the same device. If a website only prompts for an additional verification step when a suspicious login is detected, but not on each new device signing in, we do not classify that as 2FA.

If you'd like to discuss this matter further or have additional questions, please [create a new issue](https://github.com/2factorauth/twofactorauth/issues/new).

Thanks!
-- Jacob
