### ISSUE TITLE
Please add First Direct (UK)

### ISSUE THREAD

**Issue by MaplesThroughWindows** [2factorauth/twofactorauth#1535]
Hi,

http://www2.firstdirect.com/1/2/securekey/demos

A search indicated First Direct (an HSBC banking subsidiary) are not on the list yet.

Kind regards.

**Comment by fpigerre** [comment]
Hello @MaplesThroughWindows,

Thanks for creating this issue! :+1: 
It seems that some discussion regarding the addition of First Direct has already occurred in issue #1305. Please feel free to read over the discussion in that issue and perhaps submit a pull request.
At present, I have closed this issue so that we can ensure all discussion is centralized in issue #1305.

All the best,
psgs :palm_tree:
