### ISSUE TITLE
Other Category is Lacking Alphabetical Sorting

### ISSUE THREAD

**Issue by whatinthenameofgod** [2factorauth/twofactorauth#1566]
If you look in other, the alphabetical sorting is all jacked up.

**Comment by jamcat22** [comment]
@psgs It seems when we merged #1561, we removed the part of the site display that automatically alphabetizes, regardless of the alphabetization of the YAML files. Do you know how we could re-implement this?

**Comment by fpigerre** [comment]
Hello!

The issue of alphabetical sorting in the `other.yml` file has been fixed in commit baffc76dabb09799f2eb6fc69b4624080b04858c.
I don't think any code was ever created to sort websites alphabetically when the tables are generated. I think that the ordering of the YML files were usually relied on.

Thanks for pointing out this issue @whatinthenameofgod!

**Comment by jamcat22** [comment]
@psgs Sorry. I must have been thinking of another project. My bad.
