### ISSUE TITLE
Wells Fargo

### ISSUE THREAD

**Issue by sanjay** [2factorauth/twofactorauth#1582]
Wells Fargo does support two factor authentication but apparently it isn't public yet.  I stumbled on this talking to them.  They call it Advanced Access Code and it works by doing phone calls or text messages to a phone or (apparently) using a RSA SecurID hardware token.  I don't know the details on the hardware token though.  To enable you have to call them and get them to enable this - there isn't any documentation online.

**Comment by jamcat22** [comment]
Do you mean "Advanced Access"? They have a help document about it [here](https://www.wellsfargo.com/privacy-security/advanced-access).

That doesn't fit our definition of two factor authentication (or 2FA), as it only requires a security code during certain transactions. This is commonly referred to as two factor authorization, not authentication.

Please see our [note on definitions](/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) in the CONTRIBUTING.MD file, issue #1114, and PR #1115.

I'm going to close this issue for now, unless they now have an option to require codes on login.

**Comment by sanjay** [comment]
That is what I mean but this doc doesn't reflect what I've got.  I asked for this to be enabled for my account and now EVERY time I login, I have to enter the code they send in order to login.  That is 2FA in my book.

**Comment by jamcat22** [comment]
Ah. That definitely changes things! Do you have a screenshot of Wells Fargo requiring 2FA during login?

**Comment by sanjay** [comment]
Attached with the last 4 digits of my cell phone masked.  Note the tab for the RSA SecurID token.  I don't have one and I'm not sure how you add it to your account.  No support for Google Auth/Authy type codes unfortunately.

![screenshot at 2016-02-06 18 03 05](https://cloud.githubusercontent.com/assets/20825/12869943/1474371c-ccfc-11e5-9c02-c1937ef85490.png)

**Comment by f1r-CTLF** [comment]
I'll add some additional info to this, because I have personally gone through the steps to setup true 2FA on Wells Fargo.

Steps:
1) Login
2) Navigate to the 'Account Services' tab.
![001_account_services_main_clean](https://cloud.githubusercontent.com/assets/15699955/13035856/11e1c560-d30e-11e5-90cd-f7daae456a90.png)
3) Under 'My Profile', select 'Manage Advanced Access'.
4) Setup mobile phone number or RSA SecureID Device.
![002_account_services_advanced1_clean](https://cloud.githubusercontent.com/assets/15699955/13035858/1df6e858-d30e-11e5-95d5-c5d6261aa3cf.png)
5) Navigate back to the main 'Account Services' tab.
6) Under 'Security & Privacy', select 'Enhanced Sign On Options'.
7) Select your desired 2FA setting, then select Continue and follow instructions.
![003_account_services_enhanced_clean](https://cloud.githubusercontent.com/assets/15699955/13035892/e93b2b82-d30e-11e5-8157-377a234f6eeb.png)

Notes:
- I could not find documentation on the Enhanced Sign On Options settings on wellsfargo.com, but they were intuitive once I found them.
