### ISSUE TITLE
Facebook 2FA does not require SMS

### ISSUE THREAD

**Issue by edwardhorsford** [2factorauth/twofactorauth#1707]
I just set up facebook 2FA using one-time codes in 1Password - but the guidance said they only supported SMS.

**Comment by jamcat22** [comment]
Please see issue #1429. The exception text states that SMS is required for 2FA, meaning that a valid phone number that can receive texts must be attached to the account in order to activate any form of 2FA.

Furthermore, the article on the [Facebook help website](https://www.facebook.com/help/148233965247823?refid=69) states,

> Note: You need to have a mobile phone number listed on your account to turn on login approvals. You can add one to your account when you turn on login approvals.

**Comment by edwardhorsford** [comment]
My bad, sorry.

I don't think the message is all that clear, since I took it to mean that 2FA could only happen through sms.
