### ISSUE TITLE
Show main sites that support MFA?

### ISSUE THREAD

**Issue by kiwiant** [2factorauth/twofactorauth#1831]
With the list growing the sites are now categorised which I understand but its now difficult to see which sites use MFA so I can enable those.

Some suggestions to make discovering sites easier:
1. Have a list of the main sites/companies that use MFA (eg, Microsoft, Amazon, Google, Git etc). This is a smaller list and we don't need to look into every service (OneDrive, Outlook.com etc).
2. Filter results by those that use MFA and recently added/updated (often I look at the site to find sites that I can not enable).
3. Show a list of sites based on my location (eg, ASB Bank and RealMe in New Zealand)

**Comment by Carlgo11** [comment]
Hello @kiwiant,
thank you for your suggestions.
These changes you're suggesting have already been brought up in #241, #519 and #521.
Even though they're all from 2014 I'm sure we'll come around to implementing them in the future.
The reason we haven't implemented any of them sooner is probably because it's one of the harder things to do with our current setup.

Might be something @psgs will do in a new design version of twofactorauth.org (version 3?).
