### ISSUE TITLE
Be more precise about the 2FA method

### ISSUE THREAD

**Issue by ckorn** [2factorauth/twofactorauth#1844]
Background: The tool GNOME-TwoFactorAuth uses the database from this site to display a list of sites which support 2FA. Unfortunately, there are different methods for supporting 2FA and not all require to scan a QR Code. So it would be great to list the exact 2FA method the site uses.

In my example I wanted to add an account for Twitch in GNOME-2FA. Twitch however implements 2FA with Authy which does not require to scan a QR code. As it seems Twitch uses Authy's own API to make the initial connection with the Authy app.

This is the issue in GNOME-2FA:
[Bug 14](https://github.com/bil-elmoussaoui/Gnome-TwoFactorAuth/issues/14)

**Comment by RichJeanes** [comment]
We have had similar discussion in the past over how specific to be with our information and decided that simplicity is best in line with our goals (to encourage the use of 2FA by making it easier to track who and how). The main issue is the preponderance of 2FA solutions including TOTP/HOTP RFCs, Authy, Duo, Sesame, Transakt, Toopher, YubiCo, etc., etc. plus proprietary solutions like Blizzard and Steam. Trying to specify each with a column or even just an icon introduces clutter and complexity to the site.

While we love to see other developers building off of our work, we believe we can better serve our audience by focusing directly on our goals rather than trying to accommodate the goals of other projects.

**Comment by bilelmoussaoui** [comment]
Hey @RichJeanes,
First of all, thank you for your work on this! I think that an easy fix can be done by instead of having a boolean value for the software/website...(software in this case). You guys can use something like apps_support. And set all by default as à value. And change it for apps like steam, twitch where you can précise that Steam website will only use Steam official application, and Twitch works with only Authy. 
I can put an effort to implement this instead of forking the repo and reinvent the wheel..
I dont know if its clear enough. Thanks again!

**Comment by jleclanche** [comment]
Knowing the 2fa method would be very useful. UI-wise, it could be displayed when hovering the "software token" cell.

From a data perspective it's also a useful thing to have, even if it's not shown in the UI. I came here to file an issue about it - knowing whether a service advertising 2fa means an open solution like TOTP or some atrocious proprietary crap like HSBC's mobile token is a big deal.

**Comment by RichJeanes** [comment]
For someone browsing 2FA.org, the specific methods supported by a site can be found by following the documentation link (where available). Manually pulling that information and figuring out a way to provide it elegantly is a lot of work just to save a click on a link. Besides a way to provide the information to end-users elegantly, it could also add a good bit of clutter to the source files.

@bil-elmoussaoui As for GTFA, how does your application make use of 2FA.org's resources? Is it just site logos or do you pull more? (Also, out of curiosity, the screenshots on the project page show a Twitter token, but as far as I am aware, they only support SMS and, supposedly, push notification approvals through the official Twitter app. So how are you showing a TOTP token?)

If someone would like to make a PR with the feature, we would be more than happy to look at it and are always open to discussion.

**Comment by Carlgo11** [comment]
Closing this issue as there's not any code suggestions. Please make a PR with the suggested changes and we'll take a look at it.

P.S. @bil-elmoussaoui you know you can use https://twofactorauth.org/data.json to pull the data, right?
It's much easier than to pull the data periodically from github. :yum:

**Comment by Rjs37** [comment]
I came here just to bring this point up myself, so I'll add my vote to this one instead.

I've come across at least a couple of tools from that list that exclusively support Authy, and I do feel it would be beneficial for 2FA.org to clearly display when a service isn't using the typical 2FA that is found in Google Authenticator and is supported by most of the other providers (including Authy).

I think that supporting only one provider like that, could even warrant a twitter prompt similar to when they have no 2FA. I don't think they should be celebrated for being so exclusive. 

Maybe just one extra column to signify whether they support the widely accepted GA barcode method or not? I think that's important enough to distinguish.

**Comment by mxxcon** [comment]
@Rjs37 but then add another column to indicate if it supports U2F? 😉

**Comment by Rjs37** [comment]
@mxxcon I don't know enough about U2F (hardware based token yeah?), but it could be a legitimate thing to do sure. There's plenty of scope to adjust the sizings of the columns to make room: (five class for the name, one for the rest of them).

Alternative would be to use the existing software & hardware columns, and display more info there rather than just a tick box that makes it look like it supports all software/hardware based tokens respectively.

The goal as stated in the readme is: "to build a website with a comprehensive list of sites that support Two Factor Authentication, as well as the methods that they provide." I don't see it being comprehensive if it's not going to provide that sort of information.

I'd actually argue that those points are more critical than the phone and email columns for example.
