### ISSUE TITLE
Notifications or RSS

### ISSUE THREAD

**Issue by nemchik** [2factorauth/twofactorauth#1870]
I'd like some kind of way to be notified when a specific service adds 2FA capabilities so that I can be reminded to turn it on ASAP. I believe since this would be very individual to each visitor of the site, a fair alternative that may be easier to implement would be having some kind of RSS feed that has entries for when the status of 2FA availability changes for a particular site or service, and then visitors could subscribe to the RSS feed and filter it according to their preference.

**Comment by beerisgood** [comment]
I'm sure RSS would be enough and Github itself provide this ;)
https://github.com/2factorauth/twofactorauth/commits/master.atom

**Comment by Carlgo11** [comment]
Closing as the question was answered by @beerisgood.
Thanks for pointing that out by the way @beerisgood :wink:

**Comment by nemchik** [comment]
Being a little nitpicky here; The feed @beerisgood mentioned does have some good information in it, but it's not very user friendly for people unfamiliar with git. For example https://github.com/2factorauth/twofactorauth/commit/3874091264093d4f46a89817f29da70452b15b46 shows only the commit message in the feed (here it is just for example)

```
Add square cash (#1877)

* update payments with square cash

* add square cash png
```

... this tells me that a service was added to the list of things that are tracked by the site, but it does not tell me if 2fa is supported from within the feed. I am able to click to open the link to the commit but that's a bit of a technical read for the average visitor who might just be wondering if their favorite service supports 2fa. This would hold true for both newly added services or existing services.

One way to resolve this would be to simply include additional notes in the commit messages along the lines of 

> square cash currently does not support 2fa

or

> square cash has added support for 2fa

but that's up to the people making the commits, and there are many, so imposing that on the committers may be a lot more effort than it's worth.

I wish I had some more constructive suggestions rather than just the observations and opinions above, but I'm not entirely sure how to best address this other than raising the attention that it's not currently easy for newcomers.

**Comment by Carlgo11** [comment]
I honestly doubt we'll ever implement something like that.

I remember there was an issue a couple of years ago requesting something similar but most of the PRs we get contains sites that already for quite some time have had 2FA.
Sure, sometimes people are quick to make a PR when a company adds 2FA but it's maybe 1% of the time.

If you want something like that you'll either have to use the RSS feed that @beerisgood mentioned or create something of your own that does a git diff and sends notifications on new additions.

It's a so small minority of the people that would see any benefits in this that we're better off doing our ordinary work to maintain TwoFactorAuth.org instead of trying to implement something like that.

Thank you for your understanding! :smiley:

//Carl

**Comment by mxxcon** [comment]
I understand what RSS is and i use it every day, but i never bothered to look into how exactly it works. When there's something new, it does just regenerate the xml file and it's up to the rss reader to diff with previous state to figure out what changed? Or does it simply append a new timestamped entry on top and rss reader knows its previous timestamp and displays everything new?

The issue with our current setup is that it's completely static and stateless. I can't think of a way(not saying there isn't) for us to generate rss with "new" entries since the last run...Every time the site gets generated, it's as if it's the first time ever..

We could also have a manual changelog file, but it's such a drag to maintain it.
One that I do when I squash merge PRs is I clean up the commit text to only the most relevant text, I don't keep all the intermediate information.
