### ISSUE TITLE
Tracker for Spotify 2FA enhancement request 

### ISSUE THREAD

**Issue by gingerbeardman** [2factorauth/twofactorauth#2255]
https://community.spotify.com/t5/Live-Ideas/2-factor-authentication/idc-p/1017979

CF. https://twitter.com/spotifycares/status/809282742592618496

> Hey! Thanks for your feedback. You can show your support for the idea at spoti.fi/1xXMHoa to help make it happen /NY

**Comment by Carlgo11** [comment]
Hello @gingerbeardman,

Thanks for posting these links here!
When Spotify adds 2FA support, we'll be sure to list them on twofactorauth.org. 🌴

**Comment by gingerbeardman** [comment]
This is the oldest request I can find, dated 2013

https://community.spotify.com/t5/Closed-Ideas/Spotify-Login-Authenticator/idi-p/450090

**Comment by Carlgo11** [comment]
Like said previously, when they actively are working on 2FA support we'll update their status but until then there's not really much we can do. We can link to external links other than email, Facebook and Twitter for encouraging them to start supporting 2FA. This is due to current limitations with twofactorauth.org.

Thanks for the link though! I just voted 😉

**Comment by gingerbeardman** [comment]
I'm just using this issue as a tracker or place to store related links.

**Comment by gingerbeardman** [comment]
Petition to encourage Spotify https://www.change.org/p/spotify-implement-2-factor-authentication
