### ISSUE TITLE
Add Orange.fr

### ISSUE THREAD

**Issue by Amaury-DB** [2factorauth/twofactorauth#2257]

**Comment by mxxcon** [comment]
Would you like to help us by submitting a pull request with relevant data?

**Comment by Amaury-DB** [comment]
Hello,

Yes. 

Orange is à french isp.

They do not provide 2fa.

**Comment by Carlgo11** [comment]
Hello @TheAdb38!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by divayprakash** [comment]
@Carlgo11 I'll take this up, but I'm just confused about which section to put it under. If you could clarify that, I'll go right ahead.

**Comment by Carlgo11** [comment]
If it's an ISP it goes under `Utility`.

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/2factorauth/twofactorauth/issues/2257#issuecomment-272134790

@Carlgo11 I'll take this up, but I'm just confused about which section to put it under. If you could clarify that, I'll go right ahead.
