### ISSUE TITLE
Creation of International Sections

### ISSUE THREAD

**Issue by lbrunsmann** [2factorauth/twofactorauth#241]
This website is getting a lot of attention in Australia. I have also noticed that a company from Brazil is wanting to be added. In order to curb confusion, some sort of internationalization needs to be created.

**Comment by mxxcon** [comment]
What's wrong with adding sites to the current list? Why would there be confusion? Is there ever a situation where some sites offers tfa in one country but not another?

**Comment by lbrunsmann** [comment]
@mxxcon issue #166 address this. Citibank in Australia supports 2FA. Possibly a way to differentiate an Australian company to an American one. Different country laws have different security requirements.

**Comment by RichJeanes** [comment]
@jdavis This seems like something that could use some consideration. Maybe putting flags on the ones that are country specific (eg. US flag on PayPal and Apple as per #272)?

**Comment by rublon-mw** [comment]
In such cases I would just add an "alert" icon next to a check mark (under SMS and other columns; see #208). Clicking on this icon would show us the restrictions that the site implemented on each method. The user could get informed that only specific countries are supported or that 2FA is only available for customers of certain paid service plans.

In most implementations, 2FA will be available internationally and across all service plans. This is why we should not introduce drastic changes to the template.

Alert icon illustration (example):
http://premium.wpmudev.org/blog/wp-content/uploads/2012/08/wordpress-malware-alert.jpg

**Comment by jdavis** [comment]
I like the idea of an international section and like what @mwww proposes with the icon. Instead of putting it on the main page (things are getting crowded), why not make a separate international.html page that has all the exceptions and country specific solutions that offer 2FA. We can leave the homepage to be global ones.

So in the case of like #272, put a little [warning icon](http://semantic-ui.com/elements/icon.html) next to companies that dont' work in specific countries and/or exceptions.

How does that sound to everyone?

**Comment by RichJeanes** [comment]
Sounds good to me.

**Comment by rublon-mw** [comment]
Showing only the global ones on the homepage sounds good. What do we do with sites that only offer 2FA for paid accounts?

**Comment by mxxcon** [comment]
@mwww grr. Why are you complicating things? :)
I say we shame them as no 2FA. It's a despicable company if it does not value their users' safety and privacy, even on free accounts.

**Comment by rublon-mw** [comment]
I'm just trying to find an optimal solution :-) The real world is complicated. Our mission should be to catalog the 2FA landscape and to present it in the most user-friendly way.

We are currently showing sites that have no 2FA at all. They are red. Maybe those that offer 2FA with limitations (e.g. only for paid plans), should be shown with a yellow background color with a "LIMITED" button that looks like the "IN PROGRESS!" button which is being used with sites that don't offer 2FA yet. This button would link to a page of the site that would explain which users can use 2FA (e.g. a price list or a blog post).

**Comment by RobFreiburger** [comment]
What if the site automatically detected which country the visitor is from and tailored the site accordingly? I'm not sure if it's within the capabilities of GitHub Pages, but on the backend, we can still use the YAML data with two optional fields, "operating countries" and "2FA supported countries". If neither are found, it's assumed the site in question is international.

**Comment by mxxcon** [comment]
@RobFreiburger afaik jekyll templates are static files generated from yaml. Can't detect country.
How about assume 2FA is global and if there are countries where it's not available use something like http://www.famfamfam.com/lab/icons/flags/ in faded color or overlay with something like `fa-frown-o` and if country specific implementation is different overlay `fa-smile-o`. In both cases make it linkable to some relevant URL.

**Comment by lbrunsmann** [comment]
@jdavis will you be creating the international.html page? Will it have to grab the data from a new area (_internationaldata) and create to yaml entries?

**Comment by jdavis** [comment]
@lbrunsmann Anyone can create the page. And as far as how the data will be organized, that's up for debate.

Maybe think of a few different solutions and we can decide from there?

One possible solution would be adding a new field to the existing yml files that is like `international: Yes` and default No for all others. Then the index.html can just grab the ones that aren't international and the international.html file can grab the ones the are international.

Then there is your possibility but try to think of the advantages/disadvantages of each and go from there! Does that make sense?

**Comment by juju4** [comment]
I started to check services for Canada and France too
https://github.com/juju4/twofactorauth/commits/master

I think first page should be more "global" services and some flag/menu allows to get it per country. Another flag Red/Green to show bad and good players would help browsing
As for variation per country (banks for example), global page could show US first but leave a note w other referenced countries

**Comment by jdavis** [comment]
Any update on this?

**Comment by juju4** [comment]
For me (France and Canada), https://github.com/jdavis/twofactorauth/pull/387

**Comment by erintiransom** [comment]
PayPal doesn't offer 2FA in Spain as an app, just hardware token ($$$).

Twitter doesn't offer 2FA in Spain, at least if your carrier is Vodafone (2nd biggest in Spain)

**Comment by xDEADC0DE** [comment]
I'd also like to add that twitter 2FA isn't available in France either.
Basically, they do it via SMS, so they need to have a contract with local carriers. You cannot have 2FA if you can't add your mobile to your account.
You could tweet, if you use something  called "long codes" or something, but you cannot have 2FA.

So I think a big red warning sign should be put next to Twitter's name on the list. Sure they can do two factor authentication, but only in very specific cases.

**Comment by erintiransom** [comment]
Hi,

It's kind of discouraging to see that Twitter, PayPal and eBay (among others) are still on that list as OK companies. They are not, maybe in the US, but not internationally.

**Comment by juju4** [comment]
welcome to new world... one brand, tons of different process between countries and sometimes even sub-level

**Comment by joshsleeper** [comment]
I really like @mwww's idea about the Limited icon in place of the green check mark for these services. Maybe it could have a simple onclick dialog or mouseover bubble saying something like "There are reports that this type of 2FA isn't working/available with this service in the following countries:" with some kind of list/grid of non-supporting country flags underneath.
This removes responsibility from the site, since it's not saying that it 100% doesn't work (just in case someone was wrong), and we don't have to hide major services like the ones @erintiransom was mentioning from the front page just because they don't support 2FA everywhere.
Don't get me wrong, it's super silly that they don't, but I think there are better ways to present that information without hiding them from plain view.

**Comment by juju4** [comment]
@joshery420 Maybe putting a star/limited icon and infobubble like or page note with flags of countries where it applies.

What about things which are "just" non-US? bank, retail from Canada, France, UK, Romania, Brazil, ...

**Comment by erintiransom** [comment]
"Super silly" is kind of an understatement. Think of Syrians or Iranians who can get their Twitter account hacked by fascist governments. It's more like a crime by omission.

**Comment by joshsleeper** [comment]
@juju4 I think services that are popular should be on this site, regardless of whether or not they're available in the states. If a major bank/retail/whatever from elsewhere supports 2FA, then it should be added to the site imo. We'd just see the US flag in the info bubble we were talking about.

@erintiransom Right right, I agree it's a problem, but not one this site can solve, nor is it the purpose of the site. Are you arguing _for_ removing sites like Twitter from the front page, or just sharing a mutual frustration?

**Comment by xDEADC0DE** [comment]
I like that we can see that they do it via SMS.

There should be a way do show that the 2-factor auth is limited (or very limited in Twitter's case). Looking at the front page, you could feel that Google and Twitter do the same thing, but one really feels half-assed, when even their documentation is incomplete on that subject.

**Comment by lpn25** [comment]
It seems that there is no visibility at all for the 'international' issue. 
Any plans for putting an international section on the main site?

**Comment by jdavis** [comment]
I actually plan on tackling it today, @lpn25. :smile:

**Comment by jdavis** [comment]
Here's where things are at for the International Exceptions: https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#international-exceptions

How does that look? If things get too messy, we can address that later.

**Comment by juju4** [comment]
It's an option for world wide brand with different policies per countries but it said nothing about non-US companies like bank of other countries (Brazil, Canada, France, UK ...) which are still pending.
What's the meaning of "new site" label?

**Comment by mxxcon** [comment]
@jdavis what will it look like on the site?

**Comment by mxxcon** [comment]
Based on what I see in `CONTRIBUTING.md` file, perhaps it can be done using this structure?

``` YAML
websites:
  - name: Site Name
    usual: stuff
    tfa: Yes
    international:
      - 'ISO 3166-1 alpha-3': !sms !hardware !phone
```

or maybe:

``` YAML
international:
  - 'ISO 3166-1 alpha-3': "freeform text"
```

That way we can have consistent country names, consistent visual representation for exceptions and/or freeform text can even be in other languages since that information will be relevant only to people that speaks it...

**Comment by jdavis** [comment]
Right now it looks like this:
![international](https://cloud.githubusercontent.com/assets/157801/3003772/6a9c4400-dd60-11e3-824c-66060c7157dc.png)

The popup shows the text but if there's more information, we can think about putting it onto it's own page.

**Comment by xDEADC0DE** [comment]
That's great! A simple icon, a link to more info for those that require it, without clogging up the interface. Great work!

**Comment by jdavis** [comment]
Right now it doesn't support the listing of countries in which it doesn't work. Instead a general statement is just given like the screenshot from 2 posts up.

Regarding the comments that @mxxcon made, I think that the idea that he has is sound. To be able to list every single country in which it doesn't work. However the issue that I have is whether or not that is too much information?

If that is what people want, then I don't have a problem listing that. Instead the warning icon can just indicate that there are restrictions and link to a possible `international.html` page that lists every single detail.

I just need some feedback on that and whether or not that is needed. I'm a bit ignorant of the international situation; so my input is pretty uninformed.

I'm tagging a few people in hopes that they will see it and give feedback: @juju4, @lpn25, @lbrunsmann, @mwww, @joshery420, @erintiransom.

**Comment by mxxcon** [comment]
Perhaps instead of `internation.html` we can have something like `exceptions.html`. There we could list any information that does not apply to the main listing. Country limitations could be there, but also other stuff such as services that offer 2FA only for paid accounts.
Mouse-over could have text something like: `Country|Service-level restrictions, click here to see details`

**Comment by lpn25** [comment]
@jdavis: I think that there are two separate issues -- international services (i.e. ones that are mostly popular outside of the US) and international exceptions (services for which the 2FA availability or options depend on the country of usage). Could you add at least gmx.com and mail.com that I mentioned in issue #273 in the email section. Although these are owned by a German company (United Internet), they seem to be registered in the US, or at least have US contact info, so it should not be a problem to be listed there, moreover there is at least one international provider, fastmail that is already listed there. There is a chance that mail.com has a lot of users, I think at some point that service was owned by AOL. As for United Internet's other service, gmx.net, it has existed since the late 90s and is quite popular in the German-speaking countries, so it makes sense to be added in an international section, once there is one created. Once there is a proper international section, I can suggest more providers; mostly European.

**Comment by juju4** [comment]
Agree w @lpn25 2 issues
- the international exceptions: current screenshot seems got to me
- international/non-us providers: could a decision be made to include them or not? be it email provider, bank, retail, ...

As for email, you have a bunch of them here http://en.wikipedia.org/wiki/Comparison_of_webmail_providers
I'm surprise hushmail is not included in current providers being part of most security conscious (http://www.theregister.co.uk/2007/11/20/hushmail_update/), have 2FA (https://help.hushmail.com/entries/63282756-Two-step-verification)

**Comment by mxxcon** [comment]
@juju4 see #497

**Comment by juju4** [comment]
@mxxcon just an example. good it's added (but still not on front site that I checked before posting)

**Comment by erintiransom** [comment]
Quick question to American users -if there are any in this discussion besides jdavis: can you use something different than a hardware token for eBay? In the list it says only hardware token. PayPal, on the other hand, shows SMS, hardware token and software implementation, but when I try it only offers me the hardware token ($$$).

I think I'm going to cancel my eBay and PayPal accounts altogether...as if they didn't make enough money, they need to sell you hardware tokens...

**Comment by jdavis** [comment]
@erintiransom I actually just was Tweeted at today saying to update eBay's 2FA info. They are using Verisign VIP so it makes sense that it should allow hardware & software.

Here's what I was tweeted: https://twitter.com/foltzwerk/status/469111184071741441

The PayPal SMS is only through PayPal though.

**Comment by erintiransom** [comment]
No Linux version of Access Desktop :( We'll have to use our phones.

Except when I visit the eBay link via VeriSign, or the PayPal link, it always ends up redirecting me to their $$$ SecurityKey -which is currently not available, anyways. No trace of VIP, SMS or any kind of 2FA. I'm currently in the US, by the way, but my users are registered in Europe.

**Comment by jdavis** [comment]
Based off of the suggestions that I've got since my last update, here's what it looks like now. I've included the Yaml as well as screenshots.

The data is just dummy data and used as an example; I don't know if any of these Remote Access companies have restrictions.

``` yml
websites:
    - name: Join.me (w/ LogMeIn account)
      url: https://join.me/
      doc: https://accounts.logme.in/authentication/getstarted.aspx
      img: joinme.png
      tfa: Yes
      goog: Yes
      email: Yes
      exceptions: Yes
      software: Yes

    - name: LogMeIn
      url: https://secure.logmein.com/
      img: logmein.png
      tfa: Yes
      email: Yes
      software: Yes
      exceptions:
          text: "Specific exception text goes here"
      doc: http://help.logmein.com/SelfServiceKnowledgeRenderer?type=FAQ&id=kA0a0000000shEi

    - name: TeamViewer
      url: http://www.teamviewer.com
      img: teamviewer.png
      tfa: Yes
      email: Yes
      software: Yes
      exceptions:
          link: Yes
      doc: http://www.teamviewer.com/en/help/402-How-do-I-activate-deactivate-two-factor-authentication-for-my-TeamViewer-account.aspx

```

![screen shot 2014-05-23 at 3 50 01 pm](https://cloud.githubusercontent.com/assets/157801/3071752/861190e4-e2bc-11e3-8c4c-cb8fb50c2fb7.png)
![screen shot 2014-05-23 at 3 50 10 pm](https://cloud.githubusercontent.com/assets/157801/3071750/861161fa-e2bc-11e3-8554-f2722fbffbe7.png)
![screen shot 2014-05-23 at 3 50 17 pm](https://cloud.githubusercontent.com/assets/157801/3071751/861180ea-e2bc-11e3-820f-2e64eed6f405.png)

As you can see, there are 3 ways to show that exceptions exist. An icon can be placed as well as any of the three:
1. A default message acknowledging restrictions will be used.
2. The message can be replaced with a custom set of words.
3. The icon can be made into a link in which more details can be revealed such as country specific info and anything else.

2 & 3 can be combined as well.

I'm still working how to handle the link and how to give site specific stuff but I have something in mind and will update this issue as soon as I have something working. Feel free to let me know what you all think in the meantime.

**Comment by mxxcon** [comment]
I think #1 is too ambiguous to be useful with no details whatsoever.

**Comment by jdavis** [comment]
I see it as being a placeholder of sorts for gathering more information or when someone doesn't exactly know the specific restrictions.

**Comment by lpn25** [comment]
@jdavis : Please also create an international section (for sites that are mostly popular outside of the US), not just international exceptions column for the existing sites. IMHO an international section is much more important, as it adds sites that are currently not in the database. As I mentioned before, I can help adding such sites.

**Comment by jdavis** [comment]
As the above commit shows, I'm working on things on the `international` branch here: https://github.com/jdavis/twofactorauth/tree/international

Feel free to take a look @lpn25. I could use some help on deciding how to manage all the international sites.

**Comment by mxxcon** [comment]
@lpn25 i don't exactly understand why you want to keep sites that are popular primarily outside of US separate?

**Comment by lpn25** [comment]
@jdavis : sorry, I overlooked that

@mxxcon : I don't necessarily want to keep them separate. This was implied by @jdavis in issue #273  when he said that some email providers would be added once an international section is created, and he referred to issue #241 (the current one), so I just went along with that idea. But it makes no difference for me as long as one could add sites that are mostly popular outside of the US.

**Comment by juju4** [comment]
I agree w @lpn25. The most important point is making possible to add non-US site normally because for now, it all seems stalled.

**Comment by jdavis** [comment]
My main concern is that the list might get really, really long (I'm assuming this is the case, maybe not) if we don't separate sites that are country specific.

Say there is a bank that is **only** available in Brazil. Would it make sense to put next to all the other banks?

I don't know the answer, but would prefer to not add it rather than make a bad decision.

If you can't tell, I really value input and am easily persuaded if I hear good points either way.

If you all think that we should have one global list regardless, then we can do that and I'll have no problem with it. Currently I think @mxxcon is in favor of it.

What do you guys think, @lpn25, @juju4?

**Comment by juju4** [comment]
I would say it's user dependent.
A catch all international page with an easy country or sector filter would be simple and pertinent enough I think. Same could apply to US/main page so both can be mixed but an easy filter is imperative, some itunes-like instant search or similar :-)

It's also a way to compare situation between countries. Some might be in advanced, some not. How to level up the situation in the world and pinpoint what solutions are available, especially if there are local ones.

**Comment by jdavis** [comment]
Okay, based on what we've all talked about, I've updated the way the Exceptions/Restrictions work. It now works like [this](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#exceptions--restrictions).

It is live as well: [twofactorauth.org](http://twofactorauth.org) so take a look. PayPal and Apple both show the custom text version. Right now we dont' have any detailed exceptions but if we did, they would show up on the [Restrictions](http://twofactorauth.org/restrictions/) page.

I am going to tidy up the navigation a bit so be looking for that.

Any comments on what has been done so far?

Lastly, coming back to the issue at hand of international stuff that @lpn25 and @juju4 have been mentioning, this issue will stay open until we have that figured out.

**Comment by mxxcon** [comment]
It seems like "international" section would list all the sites that are "not international", ie region specific..counter intuitive.

**Comment by juju4** [comment]
Agree. One page with filter would probably be best.

**Comment by joshsleeper** [comment]
@jdavis The exceptions/restrictions look fantastic! Hopefully the community as a whole can help keep them updated. :)
Also, I agree with @juju4's latest comment.
A single page with a country filter seems like one of the cleaner ways to go.

**Comment by jdavis** [comment]
Thanks for the feedback, @joshery420!

**Comment by joshsleeper** [comment]
Of course! Sorry I've been so scarce lately haha. :)

**Comment by lpn25** [comment]
@jdavis: about the country-specific sites -- that's a tricky one. I am not sure if this is technically possible, but what about a clickable section header for these sites (without any sites listed on the main page), which opens another page where these sites are perhaps split by continent and/or sorted by country. I guess this issue is mostly with companies that have offline business -- banks, utilities etc. But IMHO large, purely online businesses, at least here in EU are rarely restricted to one or few countries (although there are exceptions) and for them there would be no need to be assigned to a specific country. Small online businesses are more likely to be restricted to even just one country, but those could be excluded from the list for now. I guess, you could just try adding some sites and see how it works and how people react. After all, this is a work in progress.

**Comment by mxxcon** [comment]
I'd like to refer again to my suggestion here https://github.com/jdavis/twofactorauth/issues/241#issuecomment-43392292
We could enter it like

```
websites:
  - name: Site Name
    usual: stuff
    tfa: Yes
    exceptions:
      - countryname: !sms !hardware !phone
```

Or flip it around and use something like:

```
   exceptions:
      - sms: !countryname
      - phone: countryname
```

prefix `!` would indicate not available there and just name would indicate available only there.

**Comment by jdavis** [comment]
While I like the idea, @mxxcon, I just wonder how maintainable/practical it is to list every country it _doesn't_ work in.

Right now what I have in place is a way to list the exceptions/restrictions in any way that people wish.  This is to allow it to be as flexible as possible.
- Duplicate the [_template.html](https://github.com/jdavis/twofactorauth/blob/master/_includes/exceptions/_template.html) and make one for the specific site.
- Add the section to the [Restrictions](http://twofactorauth.org/restrictions/) page just modify the [Restrictions](https://github.com/jdavis/twofactorauth/blob/master/restrictions.html#L43-L62) file to `include` the new site.
- Edit the site Yaml and change it to:
  
  ``` yml
  exceptions:
      link: Yes
  ```

This won't clutter the Yaml with country specific stuff and like I said, is as flexible as possible.

What do you think of that, @mxxcon?

**Comment by mxxcon** [comment]
You would use `!` exclusions in situation where something is available globally, except specific countries like North Korea(example :)).
You would use explicit listing for sites that are region-specific, for example Brazilian-only bank.

**Comment by ilyakatz** [comment]
I may be late to the party, but given there has been any discussion in a while I figured I re-open it. I think that adding a separate "international" section is very US-centric. If the goal is to keep the home page small, in the long run keeping a separate international section won't help.

Also, I'll add a little heat to the discussion. In some cases, divisions by country are not just esthetics and internationalization of the site, they are pretty much separate companies. For example, living in the US, I can open an account with [Barclays US](http://www.barclaysus.com/) but not with [Barclays](http://www.barclays.co.uk/)

**Comment by lpn25** [comment]
@ilyakatz: From what I understand, the international section was a way to include websites used mostly outside of the US. IMHO it would be better to include them in the international section, rather than not include them at all, but now the international section is not filled up and they are not included under the respective type-of-business sections either.

**Comment by ilyakatz** [comment]
I'm not disagreeing with you, what I'm suggesting is that we should not segregate US and International (aka everybody else). I'm suggesting to include all those requests for various sites/services that are used outside of US as we've been doing with all others. In the long term, when list gets too long, we would need to revise the whole site anyways and I'm suggesting _not_ to do it by US vs International

**Comment by lpn25** [comment]
@ilyakatz: this is fine with me, and I think that is even better (see #273 where I originally suggested some sites to be added to the main list of email providers, but these were postponed until international section is added). Now the situation is the worst possible -- there is no real international section, and some international sites are not added at all, while others are. I am really not sure what to think.

**Comment by juju4** [comment]
agreed w @lpn25 this subject (international section) is stalled since too long ... will lose all momentum. a pity.

**Comment by jdavis** [comment]
@lpn25 @juju4 I'm sorry for not moving faster with this guys. This is open source though so there's nothing stopping anyone (or you two) for that matter to finish up the international stuff :smile: 

I would merge it in a heartbeat if it is completed.

**Comment by dsoegijono** [comment]
@jdavis As @lpn25 said, some international sites are added to the list while others aren't; I think they should all be added, using exceptions. When the international section gets created, those sites can be moved.

**Comment by jdavis** [comment]
@dsoegijono That's definitely the best way to handle it. However bandwidth is my primary issue. I just moved across the country, started my new job and have been working another pressing project that I am working on during my free time. Luckily it is low maintenance, so when I have it done, I don't have to do much.

Anyways, like I said before, anyone can work on this. Similar to how @waako has been working on the responsive stuff.

**Comment by Carlgo11** [comment]
Added in v3.0
