### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by TJ619** [2factorauth/twofactorauth#2510]
Hello all, 

I'm from France and for me this kind of project is a really good way to progress in our security right.

I know, for me, come from an IT world, i understand what i read about the 2FA, eaven it's in english.

But if i want to share this with more "novice" poeple, it's harder for them.
So it probably (for me) a good thing to add possibility to contribute also for translation.

I don't know if it's possible to make it as easy as add site.

Wait for your answers and share about that :)

Thanks.

**Comment by fpigerre** [comment]
Hello @TJ619,

As part of our efforts to accommodate region-specific websites, we’ve been trying to find a way to display certain sites to certain users based on either geography or language, as well as translating certain portions of the website for non-English speakers.
When debating whether or not to allow users to switch the language of twofactorauth.org using a dropdown box or similar selection tool, some of the issues we came across were whether we would have to translate the notes and exceptions for all websites, and which languages should be supported.

Since Jekyll and JavaScript are used in displaying the website’s data, implementing a method for switching languages should be fairly simple. It’s unclear how translations could be maintained in the long term, however.

Issues related to translation and region-specific websites can also be found under the [international tag](https://github.com/2factorauth/twofactorauth/labels/international).

Any help with ideas related to the best way to implement translation or show region-specific websites to certain users would be very much appreciated!

Thanks,
psgs :palm_tree:

**Comment by Carlgo11** [comment]
Moved to #6166
