### ISSUE TITLE
Add link to privacy and security pages

### ISSUE THREAD

**Issue by asuh** [2factorauth/twofactorauth#2575]
This is an excellent list of websites that could go one step further and list every privacy and security page. 

Many of these websites offer privacy pages that allow further protection in addition to 2nd factor auth. Too many companies invade privacy or security by automatically opting into marketing and other ways to allow 3rd parties to know things about us that they shouldn't. This could potentially be used against us in 2nd factor auth if, for example, phone numbers are included in that data and it gets hacked.

Facebook was notorious for updating its privacy pages that opted its users into sharing more without explicit consent. This page is easy to find. Others, [like Capital One](https://secure.capitalone360.com/myaccount/banking/privacy), are buried in account pages and take a while to get to.

This could easily be in the form of another column in the `<th>` section next to Docs. I hope you'll consider adding this.

**Comment by Carlgo11** [comment]
Hello @asuh,
thank you for your suggestion!

With twofactorauth.org our goal is to inform consumers about what sites support two factor authentication. Copies of twofactorauth have been made by third parties to list things such as password policies and hardware authentication.
I think your suggestion is better suited for a copy of twofactorauth.org rather than on our site.
Since as, like the name suggests, our only goal with the site is to inform about <u>two factor authentication<u>.

In the future we might team up with someone to offer privacy page tracking but for the foreseeable future we won't.

Once again, thank you for your suggestion! 😄 

**I hope you'll have a great Saturday evening!**

//Carl
