### ISSUE TITLE
Browser Extension

### ISSUE THREAD

**Issue by willscott** [2factorauth/twofactorauth#2579]
I put together a browser extension for tracking two factor based on the database in this repository.
Initial chrome version:
https://chrome.google.com/webstore/detail/2-factor-sigil/cbdfpgmgblnhpojnhchjejiggjehinmk

Source:
https://github.com/willscott/2fsigil

The main question that came up, which seems also to be under debate here, is what to do for advocacy in helping convince sites to add two factor. Especially for users with a browser extension there's a possibility to estimate user demand ("more than 500 users have requested this feature"), rather than the current tweet flow.

**Comment by Carlgo11** [comment]
Hello @willscott,
thanks for your interest in this project.

I have a few suggestions for you.
1. We're using an MIT license so if you're going to use our intellectual property you'll have to give credit to the project.
2. Try to use https://twofactorauth.org/data.json instead of crawling GitHub. That way you use up less resources.
3. The "please add x" tickets will only end up closed by one of us if the author doesn't give any more information about the site.
For site-suggestion-tickets we want to know:
* If the site currently supports 2FA.
* The ways to contact the site if they don't support 2FA. Such as Twitter handle, Facebook page and email address.
We also prefer pull requests over issues.

And to answer your question, no there's no way for us to measure how many people request a service other than to look at the twitter flow. TwoFactorAuth is running on Jekyll which is built for static websites.
Every time a new commit is merged to `gh-pages` a new website is made from scratch.

**Comment by kenman345** [comment]
If you want, I can help modify the data.json to include the data the file has last been generated. This coul;d help by giving you a first level indication field as to whether or not any data has even potentially changed. 

Additionally, you could just have the extension hit a new json we can create that would just indicate the last time the site has been updated, so that it has less data its pulling down unless it knows it needs it.

**Comment by willscott** [comment]
@kenman345 yeah, a version to know in advance that the file hasn't changed from an already cached one would be nice. browser cache might help, but doing it explicitly doesn't seem like it hurts anything if it's easy.

**Comment by mxxcon** [comment]
But to know if a file changed, you'd need to download it anyway..so how would that give you any benefit?

**Comment by willscott** [comment]
If it's included in the top level data.json, then clients can skip fetches for individual category files that haven't been updated since the last fetch.

**Comment by kenman345** [comment]
I was saying that it might make sense as a smaller, few line JSON that indicates the last time the site was built. Its a bit more tricky to identify when a section has last been changed and add in a timestamp to that. I am not even sure with the way things are configured right now that its even possible to do that level of detail.
