### ISSUE TITLE
Clarifcation of Chase 2FA support

### ISSUE THREAD

**Issue by admoman** [2factorauth/twofactorauth#263]
I'd like some clarification of the Chase 2FA support. I can't find any way to set it up on their website or any reference to it in their security documentation. Can someone point to how to actually use 2FA with Chase?

As best I can tell, @jfocht was who added this entry.

**Comment by mxxcon** [comment]
Chase's website is very stupid/convoluted when it comes that. :(
I previously tried to find an exact link where to set it up but couldn't.
Most consistent way I found you can get that screen is if you logout, delete all your cookies for chase.com domain and try to login again. You'll get a screen saying that Chase does not recognize you and will ask to setup a _Identification Code_. You'll give your phone and/or email to verify. Next time you login from a system that doesn't have Chase cookies, they'll send you sms/email/phone call with a security number to enter at login.
Screenshots of setting it up here http://fppad.com/2011/11/29/boost-your-online-security-with-two-factor-authentication/

**Comment by RichJeanes** [comment]
I also have Chase and can confirm this is how it works. If you don't think you have it set up on your account, I'd recommend contacting support for clarification. There may not really be any documentation on it but I think that's because it is mandatory when you set up an account. If you don't access your account from new devices very often, it's easy to forget that this is a thing.
