### ISSUE TITLE
PayPal software token?

### ISSUE THREAD

**Issue by ToddHensley** [2factorauth/twofactorauth#2686]
Does PayPal actually offer a software token (e.g. Google Authenticator)? I see on their site SMS and a hardware token option, but not a software token.

**Comment by jamcat22** [comment]
Hi @ToddHensley!

They do offer a software token through Symantec VIP. The [EFF](https://www.eff.org) made a great guide on how to add it to your account, which is available [here](https://www.eff.org/deeplinks/2016/12/how-enable-two-factor-authentication-paypal).

This issue is also related to #1026.

Feel free to reopen this issue if you have more questions.

Thanks!

**Comment by Sunit-Kulkarni** [comment]
https://www.paypal.com/signin?returnUri=https%3A%2F%2Fwww.paypal.com%2Fcgi-bin%2Fwebscr%3fcmd%3d_setup-security-key

Here is that link they mention to sign up the VIP app.
