### ISSUE TITLE
Please update Trello and add ISLOnline

### ISSUE THREAD

**Issue by Nakar81** [2factorauth/twofactorauth#2703]
Add Hardware Token to Trello (Task Management)

Add ISLOnline to Remote Access section.

**Comment by Nakar81** [comment]
ISLOnline only have SMS

**Comment by lx4r** [comment]
Trello now also supports Software Tokens (authenticator app):
![trello](https://user-images.githubusercontent.com/1402895/32134293-6a861038-bbea-11e7-8cc4-ee08ef305944.png)

**Comment by Jawshy** [comment]
Hi, @lx4r. Trello was updated to list software-based 2FA support in https://github.com/2factorauth/twofactorauth/pull/2729. The website doesn't yet show this change because this and other commits need to first be merged into [`gh-pages`](https://github.com/2factorauth/twofactorauth/tree/gh-pages). For more information on the process please see [_The life of a commit to twofactorauth_](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge).

**Comment by lx4r** [comment]
Hey @Jawshy,
thanks for the quick reply and the clarification. Keep up the good work! 🙂

**Comment by Carlgo11** [comment]
As Trello have been merged and ISLOnline isn't in the top 200k on Alexa I'm closing this issue.
