### ISSUE TITLE
Update Nintendo

### ISSUE THREAD

**Issue by Lechucico** [2factorauth/twofactorauth#2742]
Nintendo recently added TFA.

**Comment by jamcat22** [comment]
I can confirm this is the case, and Nintendo Accounts now support 2FA via TOTP. Here's the [doc link](http://en-americas-support.nintendo.com/app/answers/detail/a_id/27496). 2FA is only available for and protects a [Nintendo Account](http://en-americas-support.nintendo.com/app/answers/detail/a_id/15997), not what we currently list, which is the [Nintendo Network ID](https://www.nintendo.com/support/nnid/en/). It's also not available for child accounts (users 12 years old or younger). A large issue with the system is that if a Nintendo Network ID is linked to the account, **signing in with the non-2FA protected Nintendo Network ID bypasses 2FA on the protected Nintendo Account**. While this is true for linked Facebook, Twitter, and Google accounts, each of those services also supports 2FA, while a Nintendo Network ID does not. Additionally, this is an even bigger issue as users who have owned a 3DS or Wii U have had to link their accounts in order to [combine shop balances between 3DS, Wii U, Nintendo Switch, and Nintendo's online shop](http://en-americas-support.nintendo.com/app/answers/detail/a_id/22369) and use their Mii as an avatar, meaning most long-time Nintendo users will be put at risk.

![Nintendo Account 2-Step Verification Settings Screenshot](https://user-images.githubusercontent.com/1897053/30748844-c2d33b28-9f6e-11e7-8f07-236b98cd9cc4.png)

**Comment by RichJeanes** [comment]
Sounds like a MS/Skype situation worth having a note on the entry.

**Comment by jamcat22** [comment]
Oh goodness, I just remembered all the screenshots for Skype are on my old computer. I'll have to grab them and explain on #2217. Thanks for the reminder!

I agree we should probably have an exception message about it. Maybe something like: "Linked Nintendo Network IDs and other linked social media accounts bypass 2FA. 2FA not available for child accounts of users 12 years of age or younger."

**Comment by stephengroat** [comment]
closed by #2791
