### ISSUE TITLE
Security questions

### ISSUE THREAD

**Issue by ilyakatz** [2factorauth/twofactorauth#299]
Some sites provide an extra level of security (not a great one, but still) by asking you to validate certain personal questions (eg. Tradeking, Yodlee Labs). It doesn't really fit into any of the categories provided. Should there be a separate column for that?

**Comment by ilyakatz** [comment]
Here is an example 

![Security questions](https://monosnap.com/image/MeLNj6Y5stswAPGfCQwMAjSi1iW9Q0.png)

**Comment by rublon-mw** [comment]
Since this is only based on the knowledge factor, it is not two-factor authentication, but two-step authentication:

"Two-step verification is a process involving two stages to verify the identity of an entity trying to access services in a computer or in a network. This is a special case of a multi-factor authentication which might involve only one of the three authentication factors (a knowledge factor, a possession factor, and an inherence factor) for both steps. If each step involves a different authentication factor then the two-step authentication is additionally two-factor authentication." (http://en.wikipedia.org/wiki/Two-step_verification)

Thank you for bringing this up though :-)

**Comment by ilyakatz** [comment]
@mwww thanks for the explanation. i'll leave this open for creators to ponder about. I would like to see this taken into account since it'd better than nothing

**Comment by jdavis** [comment]
Michal is completely right; passwords are stored in people's heads and so are security questions. Thus it isn't a second factor.

As far as it goes about being a separate column, I don't think it should be. While it's great that some websites use it, I don't think it's part of the movement we are campaigning for.

I hate shooting down issues like these because extra security is always great and I feel like a jerk. Keep up the great work though, @ilyakatz. It's important to ask these kind of questions.

**Comment by RichJeanes** [comment]
Seems things wrapped up pretty well here. Closing for tidiness.
