### ISSUE TITLE
"Google Auth" and "Authy" aren't descriptive or useful.

### ISSUE THREAD

**Issue by onethumb** [2factorauth/twofactorauth#30]
Both Google Authenticator and Authy implement  the same algorithm TOTP.  See:  http://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm

The only difference is GA tends to use 6-digit tokens and Authy uses 8-digit tokens.  Same algorithm, same implementation.

More importantly, there are lot of other TOTP apps & services that work great (in some cases better) and are deployed at large organizations, like Duo:  https://www.duosecurity.com/

Many of the people using those other great 2FA services won't know what "Google Auth" or "Authy" mean, when in reality, those apps & services work just fine with all the things on this list.

Maybe a more appropriate heading would be "TOTP" and the values could be 6 digits, 8 digits, or 6-8 digits, depending on the service?

**Comment by onethumb** [comment]
See Hacker News comments to the safe effect:  https://news.ycombinator.com/item?id=7414945

**Comment by onethumb** [comment]
Given how important it is to keep it simple, on further reflection I'd just change it to "TOTP" and checkmarks, rather than getting into digit length.  It's not really relevant.

**Comment by ilyakatz** [comment]
TOTP could be confusing to non-technical user, so If you do change to TOTP or something like that, I would suggest to link it to a description that provides links to google authenticator, authy, duo and others

**Comment by ryankearney** [comment]
@ilyakatz Do you really think non-technical users are going to http://twofactorauth.org/ to check if their favorite website supports two-factor authentication?

**Comment by ilyakatz** [comment]
@ryankearney 2-step authentication is becoming more and more common. As far as I know, banks in US are required it set it up now. So over time2-step will become a more common place phenomenon (unless something better comes along), so I think it is very reasonable to work on this project with assumption that it will be used by non-tech people

**Comment by jdavis** [comment]
Hmm, I totally think the two should be merged into a single column if possible. I'm going to think on this to see if there is a good way to visually indicate that Authy/GA/others are all compatible.

Let me know if any of you guys have more ideas; I'd love to hear them.

**Comment by mathstuf** [comment]
The problem with Authy-only sites is that the user never gets the key to use non-Authy applications (unless I missed something or I can't see that it's possible without having an Authy account), so compatibility is a one-way street.

Maybe just having "generic mobile app" to replace the "Google Authenticator" column with a link listing implementations (e.g., FreeOTP[1] which is a fork from the last FOSS GA release or oathtool[2] for PC usage).

[1]https://fedorahosted.org/freeotp/
[2]http://www.nongnu.org/oath-toolkit/

**Comment by jdavis** [comment]
I've seen some discussion that says that Authy uses TOTP but also their own system? Does anyone have more info on this?

**Comment by mathstuf** [comment]
AFAICT from when I was looking into it for HumbleBundle, they do TOTP for other sites, but actual Authy support does some magic on the server side which then communicates with the Authy app for their TOTP (presumably so you can't lose your secret key, but you also can't do your own backup and are locked into their app). I thought of it as something like OpenID for TOTP (which is using mechanisms I can't verify and therefore won't trust).

**Comment by clawfire** [comment]
As a user of Authy I maybe can help. It's compatible with ALL TOTP that the google app can handle. All of them. Really. But yes, website can make some kind of implementation to skip the step where you enter the code / take a picture of the qrcode by asking Authy "I got an user with this email, please add an TOPT entry for me in his app". That's it.

And for a user point of view it's nice ( but disturbing the first time )

**Comment by troyjfarrell** [comment]
As someone who has added a site that supports HMAC-TOTP but not Authy's proprietary approach (as in establishing a key via Authy's servers) I think that the Authy column should be either
1. removed because it's proprietary (and we don't have separate columns for other proprietary solutions like YubiKey, Duo Security, or AlterEgo) or
2. be made to only refer to the Authy solution and not generic HMAC-TOTP compatability (as other solutions like Duo Security's application also support standard HMAC-TOTP.)

**Comment by mathstuf** [comment]
FWIW, YubiKey has FOSS management software and you can set up your own server and certificate chain rather than using YubiCo's services (Fedora did this IIRC). I agree that Authy isn't the best since a third party has all of your secret keys in its implementation (and in official Authy support _only_ Authy has the secret (again, this is just AFAICT without signing up; feel free to correct me on that)).

**Comment by smholloway** [comment]
Thanks for the heads up, @troyjfarrell. I was trying to address this issue with https://github.com/jdavis/twofactorauth/pull/208. 

Beyond the solutions already mentioned I'll add Toopher and Rublon. There are many more. Adding one column per 2fa provider is intractable, and trying to decide who gets a column is a draining political discussion. @mwww has a good vision, I think. Essentially, move providers into the custom column and check the boxes for more abstract things like SMS and OTP. Then we create a providers page and let everyone add their favorite 2fa provider.

**Comment by jdavis** [comment]
I do like that solution as well, @smholloway. Would #208 be best to add to the next milestone, Awesome 1.0 rather than this one?

**Comment by jdavis** [comment]
Also, if issue #208 encompasses this issue and more, then I'd like to close this issue but will only do if everyone agrees that #208 is the superset.

**Comment by smholloway** [comment]
Since we're proposing a fairly large change to how things are done (existing code needs to be migrated and new PRs should conform to the new style), I'd recommend getting it in sooner rather than later. You've created an awesome project and I think that doing the work now will help it continue to flourish. I think this PR (move proprietary solutions to the custom column instead of giving each its own column) plus PR #208 (add a separate page where 2fa providers can be compared) combine to make the more scalable twofactorauth.org that continues in the spirit of your idea.

**Comment by jdavis** [comment]
I agree in that it should happen sooner. Also, let's move discussion to #208 for simplicity. Closing.
