### ISSUE TITLE
updating the site more often

### ISSUE THREAD

**Issue by kenman345** [2factorauth/twofactorauth#3106]
Hey, I noticed that the site isnt updated too often. Most of the PRs are for content updates, which the Verify.RB script run with rake and Travis-CI verify those. I am wondering perhaps why this hasnt been automated to be a better experience. Travis-CI works well with GH-Pages and can be used to automatically deploy when you tag the master branch.

That is what we do for our main releases on AcceptBitcoinCash/AcceptBitcoinCash, but we use a Docker image. We do however have Master automatically be tested with Travis-CI and then push that to the gh-pages branch with Travis-CI so we can have a live beta site via Github's services. 

I say this so you understand that if it were wanted, I could bring some of this knowledge to this project so new things merged to master cause the site to update, or make it work only when a tag is applied. But either way, I think you are greatly under-utilizing the validations you already set up and could benefit from the site being deployed as soon as new data is merged. 

LEt me know if I can help.

**Comment by conorgil** [comment]
I am new to the project, so I don't have any knowledge of history, but I also had the same question. It would be great to get continuous deployment on the site anytime something is approved by one of the maintainers. Are there any docs somewhere outlining the process to get new things live that I should read as I get up to speed?

**Comment by kenman345** [comment]
[Look at Step 5](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge)

But [here](https://docs.travis-ci.com/user/deployment/pages/) is the documentation for Travis to do the merging to gh-pages branch. Its quite easy and works well. any questionable code that could break things should be caught by unit tests anyways, and verified manually by a contributor before being merged, as is the process today, so why make deployments manual when you already built in so many validation steps. 

Note, I could also bring (, and I've mentioned it here, )[https://github.com/2factorauth/twofactorauth/pull/3067#issuecomment-378789373] that the validation `verify.rb` script can be updated to include validating the validation schema. That would help bring the tests to a space where we are testing the structure we are then going to use to validate the rest of the data set with. Though this change I would like to only make once the PR linked at the beginning of this paragraph were merged or closed as it has changes to the `verify.rb` script that would conflict but those changes are also quite valid and helpful.

**Comment by Carlgo11** [comment]
Hello @kenman345,
thank you for your suggestion.
This has been discussed internally and for the time being the process won't change.

Due to the amount of traffic I don't want to risk having the site malfunction or information be incorrect.
Before we merge master to gh-pages we check that all merges since the last time updating are up to our standards and several other checks regarding the information in the merged PRs.

Your suggestion certainly would be feasible if we only checked for site errors but that's only half of what we check before merging.

Once again, thanks for the suggestion!

//Carl

**Comment by conorgil** [comment]
@Carlgo11 Is there an issue or other public document that I can read to get background on previous discussions about this?

Also, can you elaborate on what specific checks are performed before merging `master` to `gh-pages`? Are they documented anywhere so that others can get up to speed and so that whoever is performing the merge has a checklist to follow to make sure that nothing is missed/forgotten?

I completely understand (and strongly support!) the desire to make sure that the information being published is accurate and that the site doesn't malfunction. However, there are many technical mechanisms that we can use to ensure those goals are met.

I **really** think that investing some more time into CI/CD would both increase the quality and reduce the effort to maintain the site. I would understand the hesitation of going full Continuous Delivery if not enough automated checks were in place to ensure quality. If that is the case, then can we make it a goal to move in the direction of full CD and document milestones to get us there? That way, folks will also know what automation PRs related to CI/CD would be most useful.

Thoughts?

**Comment by kenman345** [comment]
I think lots of options exist. Even just adding some extra files to help dockerize the build and have travis-ci upload the latest of master branch to dockerhub so everyone can confirm the same build would be petty easy to configure and helpful. You could even pay for a very cheap ($5 a month) VPS service and set up that it automatically pulls down the latest docker so you can make a beta page that allows you to test out on mobile and all test a live version. 

You seem to be thinking something will break the site. Thats what your `verify.rb` script helps with validations and its very rare that you have overall site strucutre changes. If you were constantly making risky changes thats one thing but you're not. You're mostly adding content in a very consistent and testable way.

**Comment by Carlgo11** [comment]
@kenman345 I think you're misinterpreting me here. Most of the checks aren't code related. It's more in the lines of phrasing and subtle information on the sites' documentation pages (or the lack of information) as well as manual review of the content of the sites.
I already have a development site linked to master for testing and easy fixes such as HTML, YAML or liquid errors are already caught via Travis before PRs are merged.

@conorgil on point 6 of the [FAQ-Merge](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge) page on our wiki you'll find that merges only are done by a few maintainers of twofactorauth.org.
I'm afraid you won't be able to update gh-pages without being a maintainer of this project.
I had a checklist/guidelines somewhere but I can't seem to find it now. Maybe it's been purged by Slack's message limit for free plans. 🤷‍♂️

**Comment by conorgil** [comment]
@Carlgo11 I know that only maintainers of the project can update gh-pages right now, but I tend to use the term "we" when I write in issues just as a nod to the collaboration among the entire community contributing to the project. Sorry if that was confusing.

Thanks for the link to the FAQ. What does the term `collaborator` mean? I take it to mean any person on GitHub who wants to collaborate to the project, similar to the list of [contributors](https://github.com/2factorauth/twofactorauth/graphs/contributors) to the repo. Is that the correct meaning? Currently, the PRs say that "At least 1 approving review is required by reviewers with write access." Isn't write access restricted to only the repo maintainers? If no, then updating the FAQ to be more clear would be really helpful. If yes, then maintainers can enforce the quality checks on each individual PR and the move to CD should be pretty painless, right?

By distributing the quality checks among each individual PR, there can be a higher number of maintainers ensuring quality of small sets of changes. The current model of lumping all PRs into the master branch and then doing a single monthly review & merge is definitely requiring a much larger time investment from individual maintainers. Whoever reviews the large monthly set of changes will have to re-review every single change to ensure quality, which will likely take enough time that maintainers (who are busy with other things) are less inclined to actually do that on a regular basis.

What do you think about changing the model so that maintainers enforce the quality checks on each individual PR and then adopting CD? As a first step in this direction, we could require each PR to receive a sign off from two maintainers so that they can check each others work.

**Comment by conorgil** [comment]
I cloned the wiki repo down and made some changes locally with the hope of opening a PR to propose a new process and start a discussion. Sadly, as I learned [here](https://github.com/isaacs/github/issues/846), you cannot open a PR for a GitHub wiki. Lame.

So, this thread seems like a fine place to continue this discussion and share my proposed process for handling PRs in the twofactorauth repo:

# Proposed process (edited from existing wiki page)

## The life of a commit to twofactorauth

These are the different steps for sites added to our list:

1. A generous GitHub user donates their time to fork the repository
   and follow the [guidelines and criteria][criteria] to add a new
   site in their fork. Then, they open a PR against the `master` branch
   of the `2factorauth/twofactorauth` repo.
2. A round of discussion begins where anyone with a GitHub account can
   comment on the PR to ask questions about the relevance of the added
   site, point out possible errors, or suggest other improvements.
   
   If a [core-team member][core] asks for changes, then the PR will
   remain in this step of the process until the PR author submits the
   requested changes and the core-team member reviews the changes.

   This is also the step where a series of automated checks will be run on
   [Travis CI][travis]. All of the [required status checks][status checks]
   in the PR must pass before moving onto the next step of the process.
3. After some discussion has taken place, one of the [core-team members][core]
   will approve the PR, which means that (s)he thinks the PR follows the
   [guidelines and criteria][criteria] to add a new site, quality checks have
   passed, etc.
4. To catch any human errors and ensure quality remains high,
   a second core-team member is required to review the PR before it can
   be merged.
5. After two or more core-team members have approved the PR, it will be merged
   to the `master` branch.
6. After the PR is merged, the `master` branch will be automatically rebuilt by
   GitHub pages and the new content will go live immediately. Everyone can
   now see the site you added! :smiley: 

_The twofactorauth project is run by a team of volunteers who do this in their spare time. Please have patience with this process._

[criteria]: https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria
[core]: https://github.com/orgs/2factorauth/people
[changes]: https://github.com/2factorauth/twofactorauth/compare/gh-pages...master
[status checks]: https://help.github.com/articles/about-required-status-checks/
[travis]: https://travis-ci.org/2factorauth/twofactorauth

# Benefits
I believe that this process has the following benefits:

1. Keeps change sets small (just a single PR), which means that review should be relatively quick.
2. Distributes the quality assurance among all of the maintainers (since any two maintainers can approve a PR to get it merged and live), which reduces the burden on any individual maintainer.
3. Reduces the time between a PR being submitted and the changes being reflected in the live site so that all end-users actually benefit from the effort of the PR author.

# Proposed steps to implement new process
1. enable protected branch configuration for the `master` branch
   * require review from 2 users with write access (maintainers)
   * require status checks before merging
   * include administrators (the rules should apply to everyone)
2. change something with Travis CI? Not sure on this one. I think it might be fine as is, since it runs checks on PRs to the `master` branch.
3. change the live GitHub pages site from the `gh-pages` branch to the `master` branch
4. Done.

I am still new to the repo. What did I miss in the steps above?

# Other ideas
It would be great to publicly document the list of quality and other considerations that maintainers follow when reviewing a PR. This will help with overall project transparency, will improve consistency between PR reviews from all maintainers, and will help PR authors make sure that they are addressing all potential concerns before opening a PR. The [CONTRIBUTING.md][criteria] doc is useful, but if there are other considerations that are not included in that doc, it would be good to get those documented somewhere.

**Comment by Carlgo11** [comment]
Hello again @conorgil,
collaborators means the maintainers for a repository, or rather the people who have write access to it.
More information about the difference between collaborators and contributors can be found [here](https://help.waffle.io/github-basics/whats-the-difference-between-a-github-collaborator-and-contributor).
This can certainly be clarified in the wiki.


As I said in [#3106 (comment)](https://github.com/2factorauth/twofactorauth/issues/3106#issuecomment-379930716), our merge process won't be changed as of now.

Regarding the CONTRIBUTING.md, I suggest you create another issue about that.
