### ISSUE TITLE
USAA supports email 2FA

### ISSUE THREAD

**Issue by coleslaugh** [2factorauth/twofactorauth#3345]
Consider updating the list to reflect that USAA supports OTP via email.

**Comment by pmocek** [comment]
Note that this is a rather obscure option.  The linked [USAA MFA page](https://www.usaa.com/inet/pages/security_token_logon_options) describes second factors SMS (as "CyberCode Text") and software token, specifically Symantec Validation & ID Protection (as "CyberCode Token"), but the only mention of e-mail I see is in a note explaining why an e-mail address is required in order to use their SMS MFA system: "If you need to log on and don't have your phone, we can send a one-time passcode to your email address."

**Comment by coleslaugh** [comment]
Good point. It looks like their documentation is out dated. Here is a screen shot of the 2fa screen when I log in. The first three bullets are the phone numbers I have with them and the last two are email addresses. I’m able to get a OTP to either email. I’m a CyberCode Text user. It looks like they added email support to the CyberCode Text option.

![4238fff2-b1bc-4f20-b9e9-8ed33a9fc597](https://user-images.githubusercontent.com/42038245/43607327-874c03e0-9663-11e8-9b54-db6ad8349108.jpeg)
