### ISSUE TITLE
Add xiaomi.com

### ISSUE THREAD

**Issue by ayanamist** [2factorauth/twofactorauth#3369]
https://account.xiaomi.com/
The account system of Xiaomi supports 2FA and provides QR code.

**Comment by mxxcon** [comment]
What is that account used for? What kind of information is contained in it?

**Comment by ayanamist** [comment]
Xiaomi account provides xiaomi cloud service including message sync, contact sync, photo sync, file sync, find my phone service, for its phone customers. 
You can refer to wikipedia https://en.wikipedia.org/wiki/Xiaomi for more info about xiaomi.

**Comment by kmpoppe** [comment]
Global Alex Rank is 1,311.
Supported 2FAs are EMAIL and SMS, the QR code supplied is to be used to directly login with the app of Xiaomi, I'm not sure if that would be seen as a 2FA possibility.
I'd have gone for a PR, but I'm unsure what category they would fit it? Cloud computing?

**Comment by mxxcon** [comment]
Probably `Other` is best suited category for now.

**Comment by ayanamist** [comment]
@kmpoppe Although QR code supplied seems to be used with app of Xiaomi, in fact it's a normal 2FA which is supported by Google Authenticator and other authenticator and can be scanned by these authenticator.

**Comment by kmpoppe** [comment]
@ayanamist I stand corrected. You can use SMS and EMAIL to recover from not being able to log in, but that's not two-factor-authentication. What I have seen in my test account is two-factor-_authorization_, when you change something, it wants a code from an email sent - but that's not authentication. 
Furthermore I was not able to make Google Authenticator scan the QR code (which is obvisious, since it leads to a https-link to accounts...).
So unless I'm doing something horribly wrong and logging into the completely wrong website, I can't see 2FA being implemented correctly.

**Comment by ayanamist** [comment]
@kmpoppe https://account.xiaomi.com/pass/auth/security/home?_locale=en
Above url can add authenticator in the page bottom.
Then use my 1Password to scan QR code from screen.
![image](https://user-images.githubusercontent.com/406779/52701113-6cf31700-2fb4-11e9-9775-b6847d8256ce.png)
1Password 7.3.657 handle this QR code without any other step. Save it and now you can get a valid token to fill in Xiaomi page to let step go through.

**Comment by Jawshy** [comment]
I see what Kai sees. There is an option to add a recovery email or recovery phone, but no option to enable two factor authentication as [defined for the purposes of twofactorauth.org](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions). 

![account xiaomi com](https://user-images.githubusercontent.com/10876578/73118342-df050780-3f4a-11ea-9051-7b8b258a894d.png)

**Comment by ayanamist** [comment]
Xiaomi disable 2FA support last year.
