### ISSUE TITLE
Add dashboard.authy.com

### ISSUE THREAD

**Issue by JaneX8** [2factorauth/twofactorauth#3376]
The Authy Dashboard can be added in the security category. It supports SMS and Software tokens.

**Comment by stephengroat** [comment]
Thanks for the suggestion @ElleshaHackett, but we've decided that we're not going to list 2fa providers (due to the potential confusion). See new Contributing Guidelines (https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines). I'm going to close this for right now, but please feel free to give us any other suggestions that you have!
