### ISSUE TITLE
Note on Southern California Edison (sce.com) 2FA

### ISSUE THREAD

**Issue by Grantlittman** [2factorauth/twofactorauth#3395]
Thanks for listing our website. I just want to point out that we do actually utilize 2FA on the site. It's invoked anytime a new user registration is initiated that would enable access to the customer's utility account.  The 2FA is a one-time pin issued via SMS, autodialed voice, or a paper code sent through the postal mail. Here's a video that walks users through that process https://www.youtube.com/watch?v=6R_NLP_lL30&feature=youtu.be

Additionally, if the customer wants to use 2FA for password reset we have that option as well. We're still deciding when to offer 2FA for other use cases and/or other multi-factor options such as biometric or authenticator apps.

**Comment by mxxcon** [comment]
@Grantlittman do you have a page somewhere on your site describing this, beyond just a youtube video, so that we can put it as our `doc:` tag.

Also you guys should really consider alternative authentication methods. At the very least _add_ alternative methods in addition to sms. SMS-based 2fa is not really secure anymore. See https://www.google.com/search?q=sms+two+factor+authentication+insecure
Even NIST [no longer recommends](https://www.pindrop.com/blog/nist-explains-proposed-ban-on-sms-for-2fa/) it as a secure authentication factor.

It sounds like your current 2fa system is used only during new user sign ups, but not actual account login. Am I correct?

**Comment by Grantlittman** [comment]
Thanks for the reply. I have asked my team to update our content on [this page](https://www.sce.com/wps/portal/home/customer-service/my-account/) to reflect the addition of the 2FA step during the "My Account" registration process. YouTube video I referenced before which highlights the 2FA step at 1m 2s is also linked from this page, but it's good feedback that it should be more overt further down the page where we describe each step.

You are correct that we currently only invoke 2FA when a new user registration occurs OR when an existing user requests a password reset. We are actively evaluating other use cases and different formats of multi-factor.

**Comment by Carlgo11** [comment]
@Grantlittman are you saying you don't require 2FA every time a user logs in? If it's only for certain actions that would classify as 2-step verification and not authorization.

**Comment by Grantlittman** [comment]
@Carlgo11 Correct, 2FA is not required with each login to the site subsequent to the initial user registration which does requires 2 Factor Authentication in order to establish utility customer account access. We separated the use cases of the initial user registration and authentication (2FA) from on-going registered user login (single factor). We are actively evaluating other uses cases and different formats of multi-factor authentication beyond the SMS/voice/postal one-time code.

I'm not familiar with distinction you're making on this from a definition perspective.  When I look at NIST for "[multi-factor authentication](https://csrc.nist.gov/Glossary/?term=156#AlphaIndexDiv)" I don't see any specific use case(s) which put a boundary on the term.

**Comment by mxxcon** [comment]
@Grantlittman We have distinction between _authentication_ and _authorization_ explained here https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions

**Comment by Carlgo11** [comment]
I got told that I were wrong about authorization (whops), but since it's only used for password reset it would mean SMS is the only factor used and so that wouldn't be two factor authentication. Also, if one is able to login without the second factor then there's no real reason for us to list it here.
