### ISSUE TITLE
additional custom field: trusteer, virtualkeyboard, sms-add-transfer-account, ... and few questions

### ISSUE THREAD

**Issue by juju4** [2factorauth/twofactorauth#352]
Hello,

Many banks on the international are recommending to use trusteer on your desktop or mobile to watch/browse securely your bank. 
For France (and probably others outside of north america), there are 2 security mecanisms:
- virtual keyboard: type your code with mouse and not keyboard (and additionaly, some form-grabbing protection but not always)
- sms authentication but only when adding an account for transfer.

It would be nice if those 3 options could be rendered visible.
While not replacing full 2FA, it minimizes the risk well on the thing which is sensitive (the transfer)

For retailer, I wish custom allow to show payment restrictions like
- using only national bank card
- allow international card: visa, mastercard, amex
- paypal
- gift cards
- bitcoin, other alternate currencies

Thanks for this great idea to share 2FA sites!

**Comment by jdavis** [comment]
Hey @juju4,

We are working on changing the site up a bit to account for alternate methods. Take a look at #333 and see if that fits your fancy.

Also regarding the other 2 security mechanisms. While the keyboard one is neat and protects against keyloggers, the problem is that it doesn't appear to use a second factor.

Thanks for the compliments on the site though!

**Comment by jdavis** [comment]
I think this has been addressed. I'm closing this to clean things up a bit.
