### ISSUE TITLE
Simplii Financial now supports SMS/CALLING verification

### ISSUE THREAD

**Issue by GregoryGHarding** [2factorauth/twofactorauth#3555]
would someone be able to update this in the repo? im traveling for work and unable to do so

**Comment by Carlgo11** [comment]
Hello @GregoryGHarding,
we'd need a bit more information before creating a pull request.
What's their url?
Do they have any documentation to back this up? if not, could you provide screenshots of the login/setup process?

**Comment by GregoryGHarding** [comment]
https://twitter.com/SimpliiFin/status/1063138346988384257
https://www.simplii.com/en/faq.html
Legal -> I was notified by Simplii about Simplii Financial Online Banking security enhancements. I was asked to update my contact information. What is this about?

**Comment by mxxcon** [comment]
@GregoryGHarding based on what I read in that twitter message and on their site, it sounds like it's more of a two-factor _authorization_ rather than _authentication_.
Please see this section on the distinction between the two https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions
So from the point of view of our site, it's still considered `tfa: no`

**Comment by kmpoppe** [comment]
Closing this Issue, for now, as I can't find any documentation on the site that they really use 2F-Authentication.
