### ISSUE TITLE
Accept documentation pages behind a login screen?

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#3570]
@mxxcon pointed out on Slack that there's really no reason any longer not to add documentation pages that are behind a login wall.

The reasoning for not adding it in the first place was that we're unable to validate that the service supports 2FA (in the sense of our [definition](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) but since we have started validating services by asking the authors to provide screenshots of the login or setup process if no documentation is provided, the same could be done if the documentation requires authentication in order to be viewed.

If there's another reason that I've missed then please point that out in the comment section below.
Other than that I suppose we could do a vote on the matter? I suggest using the `👍` `👎` reactions to this issue in order to vote.

**Comment by mxxcon** [comment]
Seems like unanimous vote 3 people? ;)

**Comment by Carlgo11** [comment]
I think we need a few more votes than that 😜

**Comment by Carlgo11** [comment]
@2factorauth/collaborators more votes are much appreciated!

**Comment by stephengroat** [comment]
Makes the docs (most likely) impossible to remotely validate and upkeep pretty much impossible.

**Comment by mxxcon** [comment]
Does that counterweight usefulness of having such links readily available to users of those sites?

**Comment by stephengroat** [comment]
great point, it's a tradeoff. my personal feeling is that if a user has issues on the site (links 404ing), they'll loose trust in the the site and not come back. maintenance is already hard to come by, this makes it even harder

**Comment by kmpoppe** [comment]
My eternal gratitude goes out to the genius that invented the exception-box in the UI 😉...

I added `doclogin: Yes` to Barclays UK (where the doc funnily enough gives a 404) - made a tweak to desktop-table.html and this would be a possible outcome:
![grafik](https://user-images.githubusercontent.com/24451207/56486749-0b31ba80-64d9-11e9-8fd0-aa1c899debc9.png)

Would that be a compromise?

**Comment by kmpoppe** [comment]
Bump @2factorauth/collaborators any ideas on this possible solution?

**Comment by Carlgo11** [comment]
I don't think it should be added. I've spent hours this week going through documentation links here. If they're behind a login wall we can't validate that the site uses 2FA or that the link is valid any longer. Many doc links 404 due to bad web administrators.

**Comment by dsoegijono** [comment]
(reviving this thread)

I'd say it's better to have it with the note that it requires login, plus we can ask the PR submitter to provide a screenshot. Similar to how we verify tfa without documentation.

**Comment by onkarshinde** [comment]
As a user of the website I am against this. It doesn't make sense for the documentation of secure login to be behind login. It is better to mark such websites as not supporting 2FA.

**Comment by mxxcon** [comment]
> 
> 
> As a user of the website I am against this. It doesn't make sense for the documentation of secure login to be behind login. It is better to mark such websites as not supporting 2FA.

So I have an account at a website X. I go to https://twofactorauth.org, look through the list of all the sites, see that my website X is listed as `tfa: no`. I assume that twofactorauth.org website has the correct information and as such I don't go enabling tfa on my account.
So now my account is not as secure as it could've been purely because documentation is not publicly available, defeating the purpose of twofactorauth.org?
So what kind of service are you doing to users by telling them misleading info that website doesn't have tfa even though it does....

**Comment by onkarshinde** [comment]
> 
> 
> > As a user of the website I am against this. It doesn't make sense for the documentation of secure login to be behind login. It is better to mark such websites as not supporting 2FA.
> 
> So I have an account at a website X. I go to https://twofactorauth.org, look through the list of all the sites, see that my website X is listed as `tfa: no`. I assume that twofactorauth.org website has the correct information and as such I don't go enabling tfa on my account.

At this point you should ask/complain on the official support forum of the respective website about why they do not offer 2FA. They then would point you the documentation. You may choose to then ask them why this documentation is not public.
Now imagine a scenario where I want to choose an email provider and one of the criteria I have is that their web interface should have 2FA. How exactly am I suppose to make that decision if the 2FA documentation is behind a login. Am I supposed to sign up for the service just to see if it satisfies my criteria?

> So now my account is not as secure as it could've been purely because documentation is not publicly available, defeating the purpose of twofactorauth.org?
> So what kind of service are you doing to users by telling them misleading info that website doesn't have tfa even though it does....

- twofactorauth.org is built on crowdsourced data. Shouldn't the data be independently verifiable? How is that achievable without public documentation for various websites we have included in the list?
- What happens when a contributor who requested a site to be added/updated based on docs behind login is not interested in keeping the data updated. Are other contributors expected to sign up for the service just to check if the data is still relevant or not?

**Comment by mxxcon** [comment]
> At this point you should ask/complain on the official support forum of the respective website about why they do not offer 2FA. They then would point you the documentation. You may choose to then ask them why this documentation is not public.

No. At that point I will realize that the information on twofactorauth.org website is inaccurate and I shouldn't waste my time on it as my primary source of which sites to enable tfa on. If a perfectly valid website has tfa but you direct me to complain to them on Twitter, email, Facebook, whatever to add support to it only to be told that they do have it, you are making me look stupid.
But that's just my opinion as a user 🤷‍♂️

**Comment by dsoegijono** [comment]
The site’s main goal is to list TFA availability, not how good/open their documentation is. We already list TFA sites that don’t even have documentation. I’d say doc behind login is a step better than that, so we should accept it.

**Comment by phallobst** [comment]
Since we don't seem to have enough suggestions for this issue, here another one :wink:
Sites that provide documentation only after login get a `doc:` link to (a comment in) the corresponding PR on GitHub where
1. the actual link is given
2. screenshots are included for those users that would like to check the site beforehand

Additionally, I propose that a PR without a public doc link needs to provide at least these screenshots, plus a restricted doc link if available. Unfortunately, that does mean that the PR must be amended afterwards in order to include the newly created `doc` target, but since this only applies to very few sites, it should be manageable.
