### ISSUE TITLE
Microsoft now supports WebAuthn

### ISSUE THREAD

**Issue by freaktechnik** [2factorauth/twofactorauth#3581]
In Edge on the correct Windows version at least. But that makes it work with hardware tokens. But with a big asterisk, since they don't just support it in general.

See https://www.microsoft.com/en-us/microsoft-365/blog/2018/11/20/sign-in-to-your-microsoft-account-without-a-password-using-windows-hello-or-a-security-key/

**Comment by onkarshinde** [comment]
**Disclaimer: I am not a user for Microsoft services so I could not care less for their security mechanisms.**

Microsoft is only planning to support FIDO2 (as per the announcement) and not U2F. So far I have only seen announcement from Yubico that have launched FIDO2 compatible keys.
So does it make sense to say Microsoft supports 2FA with hardware token if more than 80% of the security keys currently owned will not work on their service? Also remaining 20% will probably only work if you happen to be using Edge with a minimum version.

If we must add this then I suggest that we add an exception text as well.

**Comment by Carlgo11** [comment]
As edge is just a middleman for the authentication there's no reason to list it on our site.
Thanks for the info though! 👍

**Comment by RichJeanes** [comment]
@Carlgo11 I believe the suggestion was to add Hardware support to Microsoft accounts with an exception that it only work in Edge. I do not believe the suggestion was to add Edge itself.

**Comment by onkarshinde** [comment]
Does this exception text look okay?
*Hardware token supporting FIDO2/WebAuthn can only be used in Windows 10 version 1809 and above using Edge browser.*

**Comment by prajaybasu** [comment]
> As edge is just a middleman for the authentication there's no reason to list it on our site.
> Thanks for the info though! 👍

@Carlgo11 

Microsoft accounts use standard FIDO2 keys. They should be listed.  

Microsoft has specific [FIDO2 key requirements](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-passwordless#fido2-security-keys) that are only supported by Microsoft Edge and Firefox browsers using Windows 1809's new Security APIs. Specifically, the FIDO2 keys need to support usernameless login (login without a username).   

Microsoft has successfully implemented full FIDO CTAP2 authentication support in Edge, including usernameless logins (both Chromium based and EdgeHTML (UWP) based, on Windows v1809 and up). 

Firefox has also [successfully implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1508115) full FIDO CTAP2 authentication support in Firefox on Windows v1809, including usernameless logins. 

Chromium however, [has not fully implemented CTAP2 support yet](https://www.chromestatus.com/feature/6288375388569600) and only supports passwordless logins using FIDO CTAP2 on both Android and Windows. Google accounts only require passwordless support, hence they work with Google accounts and FIDO2 tokens.

Android and Windows Hello are both FIDO2 certified Platform Authenticators, however only Edge on Windows supports usernameless login, which is required by Microsoft accounts, whether it is using Windows Hello or an external security key. I am not sure if Android supports passwordless logins, or if it is a browser limitation due to Chromium's incomplete support.      

Unlike a lot of other services, Microsoft does not support FIDO U2F (CTAP1), only FIDO2 CTAP2 keys that meet their requirements. Warrants a disclaimer but this is totally standard. YubiKey 5 (a really popular brand) supports FIDO2 CTAP2 usernameless (up to 25 resident keys).  
Also, Firefox and Edge on Android don't support FIDO2 at all right now, not even U2F AFAIK. 

You can use [this](https://fido2.azurewebsites.net/overview) website to test passwordless and usernameless logins. The latter only works on Edge and Firefox on Windows.

**Comment by freaktechnik** [comment]
Pretty sure Firefox supports it by now? Haven't tried myself since I'm not on windows: https://blog.mozilla.org/security/2019/03/19/passwordless-web-authentication-support-via-windows-hello/

**Comment by prajaybasu** [comment]
> Pretty sure Firefox supports it by now? Haven't tried myself since I'm not on windows: [blog.mozilla.org/security/2019/03/19/passwordless-web-authentication-support-via-windows-hello](https://blog.mozilla.org/security/2019/03/19/passwordless-web-authentication-support-via-windows-hello/)

I've just realized though, this isn't really 2 factor authentication. This is just passwordless authentication via a strong hardware backed (single) factor. I don't know if FIDO2 CTAP really belongs on twofactorauth.org?  

Perhaps it is most suitable for dongleauth.info only

**Comment by prajaybasu** [comment]
> Pretty sure Firefox supports it by now? Haven't tried myself since I'm not on windows: [blog.mozilla.org/security/2019/03/19/passwordless-web-authentication-support-via-windows-hello](https://blog.mozilla.org/security/2019/03/19/passwordless-web-authentication-support-via-windows-hello/)


Yes, Firefox has fully implemented CTAP2 including usernameless logins on Windows 10 v1809+. I updated my previous reply.

**Comment by kmpoppe** [comment]
Closed with #3718
