### ISSUE TITLE
Navy Federal Credit Union 2FA

### ISSUE THREAD

**Issue by jprice8006** [2factorauth/twofactorauth#3769]
Navy federal doesn't support software token.  They use their own iOS App for an app push, SMS or email for 2FA.  My only problem is now 1Password is alerting me that I don't have 2FA setup while I do.  I would move to 1Password if I could.  I can send screenshots if necessary.

**Comment by Carlgo11** [comment]
@jprice8006 the classification is correct as a push notification still is 2FA through software.

1Password are able to ignore/blacklist specific sites so that they don’t show up in 1Password as supporting 2FA.
You should contact them about the issue.
Just describe the problem and include the URL and I’m sure they’ll help you out. 🙂

**Comment by jprice8006** [comment]
Thanks so much. I will hit them up. Love what you’re doing!

[Edited by @jamcat22: Removed email signature to protect personal info.]
