### ISSUE TITLE
Automatic favicon grabber

### ISSUE THREAD

**Issue by jtagcat** [2factorauth/twofactorauth#3827]
Could we implement [this](https://realfavicongenerator.net/api/download_website_favicon), with some image compression algorithm?

**Comment by Carlgo11** [comment]
Hmm, I don't know in what part of the process something like that could be implemented 🤔 
We can't do it as the site is being built because GitHub doesn't allow scripts to be run during that process.
One way would be to do it via JS but that would mean that every single site being viewed on twofactorauth.org would cause an API call to the service and that would both be above the monthly quota and take a really long time loading.

**Comment by jtagcat** [comment]
@Carlgo11 how much hosting do you need?

**Comment by Carlgo11** [comment]
>How much?

I don’t know how to quantify hosting.

**Comment by kmpoppe** [comment]
/me has a solution up his sleeve that works for local work. Will tell you
tomorrow.
// Kai

Carlgo11 <notifications@github.com> schrieb am Fr., 19. Juli 2019, 19:53:

**Comment by jtagcat** [comment]
@Carlgo11 well it's a light site, how much traffic I meant.
You could maybe consider using something like firebase as well, if you trust google and dont't have a ton of traffic.

**Comment by Carlgo11** [comment]
No we won't move away from GitHub-Pages. At least not at the moment.
GH-pages adds a layer of transparency that we can't get with any other hosting service.

**Comment by jtagcat** [comment]
Then,
