### ISSUE TITLE
Wildcard / Subdomains

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [2factorauth/twofactorauth#3835]
Is it possible to add urls with wildcards like *.domain.com, needed in #3834?

**Comment by kmpoppe** [comment]
Hello @alexplusde and thank you for your contribution in #3834.

Currently, wildcards are not possible as Jarvis checks every URL in the list for existence. Additionally, I have seen no implementation of a service (like Browser-plugins and 1Password), that really care for anything else than the main-domain and tld part of the URL itself to guess whether 2FA is available or not.

In the end the question would be: If weclapp.com hosts the ERP for its customers, does each and every company get the possibility to use 2FA because the login is not managend by the hosted company but by weclapp? In that case, the subdomain-part is meaningless because it's weclapp offering 2FA, not the implemented website.

Additionally, to comply with our guidelines, a domain has to have an Alexa rank < 200k. Alexa site ranking doesn't care for subdomains and only meters the main domain, so it would be next to impossible to figure out the overall ranking of that subdomain (where in the case of weclapp, I bet, customers wouldn't want the information of them using the service to be publicly available).

**Comment by AWqxKAWERbXo** [comment]
> If weclapp.com hosts the ERP for its customers, does each and every company get the possibility to use 2FA because the login is not managend by the hosted company but by weclapp?

That's true. Every user in every hosted instance has the possibility to activate 2FA.

> so it would be next to impossible to figure out the overall ranking of that subdomain

> Additionally, I have seen no implementation of a service (like Browser-plugins and 1Password), that really care for anything else than the main-domain 

So I guess it's fine then to just consider the domain.

Thank you for taking care of my PR and the detailed feedback!
