### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by noammiz007** [2factorauth/twofactorauth#3865]
Please add dark mode toggling button and make it save on cookies.

**Comment by seekheart** [comment]
One suggestion I can make, you could download dark reader for chrome which would give you a dark theme for now

**Comment by Rfosu2k2** [comment]
Without having to use cookies this would be an option as more browsers and OS's move forward with a dark/light theme.  At this time it appears that less than 10% of users have this option enabled:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
https://caniuse.com/#search=prefers-color-scheme

Otherwise it seems that it would be necessary to use CSS & scripting (JavaScript, JQuery) to enable a toggle switch on the site to cover all users.  Having enabled cookies to store a user preference is not necessary using scripts if not needed.

Here is an example using CSS/JavaScript that has cookies stored locally which could be removed:
https://codepen.io/ananyaneogi/pen/zXZyMP

**Comment by phallobst** [comment]
Please keep in mind that many website icons assume a light background, since they are transparent and/or translucent PNGs. The same probably applies to the category icons as well.

**Comment by Carlgo11** [comment]
Fixed in v3.0
