### ISSUE TITLE
Tools logos

### ISSUE THREAD

**Issue by Ritchie007** [2factorauth/twofactorauth#400]
Hi,

The way the table has evolved, is kind of too reductive.  The check marks complicate things, in that it tells us that a feature is supported but it is not enough.  If you want to know hows, you have to click on the Docs link.

In the age of Logos, all the different tools have their own logo (be it software, hardware or other).

Why not put the Logos instead of the big green check marks.  It would tell us immediately how 2FA is supported by the site in question.  No need to click on the Docs to find out.

Example : I'm a big fan of Google Auth.  If I have a choice between two sites for something, and that both support 2FA, I will tend to go with the site that support Google Auth.

In the current version of the table, I'd have to go to the Docs of each site to find out which one supports it.

Furthermore, a site being advised to support 2FA, might want to come and see which of their competition support what in order to prefer a method over another one.

Cheers,

Ritchie

**Comment by jdavis** [comment]
Hey Ritchie,

We explicitly moved away from this because of how many different implementations there were: #333 discusses this.

However, it has been discussed about adding an "Advanced" view that explains more in depth. That would take more work though but something to consider. Check out #371 for more discussion on this.
