### ISSUE TITLE
Add hosttech.ch

### ISSUE THREAD

**Issue by Jerome2103** [2factorauth/twofactorauth#4100]
Add Hosttech.ch as Hosting/VPS
FA2 typ: "Software Token"

HowTo:
https://www.youtube.com/watch?v=8T4MS0udwjI

**Comment by kmpoppe** [comment]
Hello @Jerome2103, unfortunately, hosttech.ch does not fall within No. 4 of our [Contribution Guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) because it's not within the top 200k Alexa site ranking.
If the upward trend of the last 90 days keeps continuing, it should reach that 200k soon.
Please reopen another issue by that time.
Thank you for your contribution and your understanding!
// Kai
