### ISSUE TITLE
1Password's response

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#422]
1Password isn't a hosted solution. It probably doesn't belong on the list as they pointed out: https://twitter.com/1Password/status/453706163402444801

**Comment by mxxcon** [comment]
I disagree with this.
Two factor authentication is considered to be: something you know(your username/passwords) _and_ something you have.
It seems like we slowly transitioned into thinking that "something you have" means only OTP for online services. But this not the case.
For example take KeePass(http://keepass.info/features.html) password manager.
It supports encrypting your database with your master password AND/OR a key file.

To quote their site:
- One master password decrypts the complete database.
- Alternatively you can use key files. Key files provide better security than master passwords in most cases. You only have to carry the key file with you, for example on a floppy disk, USB stick, or you can burn it onto a CD. Of course, you shouldn't lose this disk then.
- For even more security you can combine the above two methods: the database then requires the key file and the password in order to be unlocked. Even if you lose your key file, the database would remain secure.

So two-factor authentication is not only for online services. It can be OTP solutions, but it can also be encryption key files, solutions like YubiKey or even nfc and lower-power bluetooth.

**Comment by jdavis** [comment]
Okay, I am not opposed :+1:

How should we handle 1Password? Should there be a section for apps? What do you think, @mxxcon?

I'd also love input from some of the other active people lately: @jamcat22, @ilyakatz, @smholloway

**Comment by mxxcon** [comment]
I don't think a separate section is necessary. 1Password fits into our existing sections along with LastPass and KeePass.
1Password would marked as "no" and if we were to add KeePass it would be marked as `software: yes`

But yes, more input from other folks would be nice.

**Comment by ilyakatz** [comment]
I vote to keep separation by use case (the sections that exist now) and not implementation (cloud vs app). The line between an offline app and cloud service is kind of blurry in many cases

**Comment by jdavis** [comment]
Okay, the reason I asked about the separate section was, as trivial as it sounds, because the description of the site is 'List of sites...'

My brain just didn't like the mismatch.

**Comment by jdavis** [comment]
I'm totally cool with adding it as is to Identity section.

**Comment by jamcat22** [comment]
I agree with @ilyakatz. We should keep it separated by use case.

**Comment by jdavis** [comment]
I love Git. This is how easy it was to re-add 1Password:

``` bash
$ g cp b6223d85c516b0b173ba32c8c5b49cc04ff1f5ad
```

b6223d85c516b0b173ba32c8c5b49cc04ff1f5ad was the commit when @mxxcon added 1Password =]

**Comment by mxxcon** [comment]
interesting..will see what it looks like in the history once merged

**Comment by jdavis** [comment]
Disregard the first commit, I forgot that I'd be the COMMIT_AUTHOR and you'd be the AUTHOR; I re-commited it. Probably bad practice but we'll see...
