### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#4309]
It would probably be a good idea to add a template for requesting new sites.
Any ideas on how it should be structured? Here's a draft of what I've come up with.

```
<!-- Official name of the site -->
* Site name - ``

<!-- Link to the main page -->
* Site URL - ``

* Does the site support 2FA? - ``

<!-- ## The following questions are only for sites which currently support 2FA ## -->

<!-- Link to documentation on how to enable 2FA on the site -->
<!-- Attach screenshots of the setup/login process if no documentation link is available -->
* Doc URL - ``

<!-- What different implementations of 2FA does the site support? -->
* Software:
  - TOTP (RFC-6238) [ ]
  - Proprietary [ ]

* Hardware:
  - U2F keys [ ]
  - WebAuthN [ ]
  - Other [ ]

* Phone calls [ ]
* SMS tokens [ ]
* Email tokens [ ]

<!-- The following questions are only for sites which do not currently support 2FA -->

<!--- The Twitter handle of the site -->
* Twitter handle: `@`

<!-- -The Facebook handle/link for the site -->
* Facebook link: ``

<!-- The following questions are for all sites -->

I have checked that the site hasn't been suggested before - [ ]

The site is ranked below 200,000 on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following: [ ]

The site or service does not contain or promote pornographic, discriminatory or unlawful content - [ ] 
The site or service does not contain or promote pornographic, discriminatory or unlawful content  as stated in the [Exclusions](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md) - [ ]
```

_Closes #2318_

**Comment by Rfosu2k2** [comment]
Looks great, just a few items I suggest below.

1. Add a placeholder to add screenshots between these lines(or at the bottom).
 * Doc URL 
 `Screenshots if no documentation link available`
 * What different implementations of 2FA does the site support?

2. Add the Email 2FA
* Phone calls [ ]
* SMS tokens [ ]
` Email [ ]`

3. Replace the word haven't with hasn't.
I have checked that the site `hasn't` been suggested before - [ ]

4. Add the link for clarification stated in EXCLUSION.md.
* The site or service`as stated in the [Exclusions](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md)`does not contain or promote pornographic, discriminatory or unlawful content - [ ]

**Comment by phallobst** [comment]
I suggest to change the text to
`Link to documentation on how to configure 2FA on the site` (instead of `enable`), because in some cases (banking) 2FA is mandatory, but the user may choose different methods.

The exception text and icon can probably be left out of the issue template (or make it optional?). If you happen to plan a PR template as well, they should be included there.

**Comment by phallobst** [comment]
> The site or service as stated ...

I would rather put it the other way around:
> The site or service does not contain or promote pornographic, discriminatory or unlawful content as stated in the [Exclusions](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md) - [ ]

**Comment by Carlgo11** [comment]
@phallobst changed 😃

**Comment by Rfosu2k2** [comment]
1. Should you also create a link for [RFC-6238](https://tools.ietf.org/html/rfc6238) since it is included?

2. Should there possibly be a link to the wiki [Categories](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Categories) page to give examples, or clear definition of the different forms of 2FA?

3. Based on the [WebAuthn](https://en.wikipedia.org/wiki/WebAuthn) documentation, it is authenticated using either hardware or software authenticator's.  Should this not be included?  If it is included you should lowercase the "N" at the end of WebAuthn to correctly match how it is used.

4. Should the line `I have checked that the site hasn't been suggested before` include [Issues](https://github.com/2factorauth/twofactorauth/issues?utf8=✓&q=) or [Pull Requests](https://github.com/2factorauth/twofactorauth/pulls?utf8=✓&q=) to indicate where to look.
If so, the line could be changed to `I have searched the [Issues](https://github.com/2factorauth/twofactorauth/issues?utf8=✓&q=) and [Pull Requests](https://github.com/2factorauth/twofactorauth/pulls?utf8=✓&q=) to confirm the site hasn't been suggested before`

**Comment by phallobst** [comment]
It still says
> The site or service **as stated in the** does not contain...

That is some residue from before, I guess.
