### ISSUE TITLE
Change ranking on mobile to match that of desktop

### ISSUE THREAD

**Issue by leggomyinfo** [2factorauth/twofactorauth#4531]
By swapping the position of the hardware and software tokens, the ordering of the columns would mirror the degree of security each option generally provides (left:right, least:most). It currently seems arbitrary. Am I missing something?

**Comment by Carlgo11** [comment]
The positions of rows in the table aren't meant to signify degrees of security.
Security is relative and what's secure in your case might not be for someone else.

In some cases email could be much more secure than some proprietary software solution or hardware tokens.

I agree with you that something could be done to signal to the user how good the 2FA options that a site offers are but I think that should be done on a site to site basis rather than signalling that all  software solutions are better than hardware tokens etc.

**Comment by leggomyinfo** [comment]
Is the order of columns arbitrary then?

Of course the security of each option cannot be ranked in the same order for every single person. _For most people_ **and** _as a technical matter_, however, SMS/phone call is the least secure (due to SIM swapping) and a hardware token is the most secure (key cannot be cloned as easily as a software token).

I'm not proposing twofactorauth.org should position itself as prescriptive. I'm arguing that an organizing principle is preferable to none at all, and the organizing principle I'm suggesting is _generally_ true. Our standard shouldn't be _literally_ universally true or nothing at all.

**Comment by phallobst** [comment]
The order on the mobile page is equally random (but different):
- Hardware
- U2F
- Software
- SMS
- Phone
- Email

(Ignoring the fact that _TOTP_ and _Proprietary_ are not distinguished, but _Hardware_  and _U2F_ are...)

The orders on both pages should be consistent. And if we're fixing that anyway, we could go for ranking the methods in order of "perceived security" as well.

**Comment by Carlgo11** [comment]
> The order on the mobile page is equally random (but different):
> 
> - Hardware
> 
> - U2F
> 
> - Software
> 
> - SMS
> 
> - Phone
> 
> - Email
> 
> 
> 
> (Ignoring the fact that _TOTP_ and _Proprietary_ are not distinguished, but _Hardware_  and _U2F_ are...)
> 
> 
> 
> The orders on both pages should be consistent. And if we're fixing that anyway, we could go for ranking the methods in order of "perceived security" as well.

But if we are to actually put them in a particular order based on perceived security we'd suddenly start ranking 2FA options (and in many cases wrongly ranking them).

Having them random is they are now means we haven’t actually put values on the different options.

**Comment by leggomyinfo** [comment]
Can we all agree that the order across desktop and mobile should at least be consistent?

If so, here are the three types of users as it relates to our two options (chime in with what I might be missing).

**Group 1:** users who appreciate the differences between 2FA and will likely recognize a generally-true-ranking logic
_- with random order:_ will have a bit more difficulty scanning the results (which has been my experience, hence my proposal) and will make their own informed decision regardless of the order
_- with ranked order:_ will have a bit easier time scanning the results and will make their own informed decision regardless of the order

**Group 2:** users who do NOT appreciate the differences between 2FA and assume the order is random
_- with random order:_ no better or worse off
_- with ranked order:_ no better or worse off

**Group 3:** users who do NOT appreciate the differences between 2FA and assume the order is logical (perhaps based on degree of security, or something else)
_- with random order:_ same or (arguably) worse off
_- with ranked order:_ same or (arguably) better off

I would tend to agree with @Carlgo11 if we were also considering adding an accompanying explanation. Absent an explanation, I don't see any potential harm from using an _internal_ logic.

**Comment by Carlgo11** [comment]
@djfredalert here are some setups that don't follow your suggested order.
1. PGP encrypted email containing OTP => email is superior to anything else.
2. Bank identification with public private keys => superior to hardware.
3. Hardware is in the form of a paper card with codes (used by my bank and by lastpass) => hardware implementation is inferior to all the other forms.
4. Password for email is the same as for the login site => Email auth is inferior to any other form.
5. Phone carrier uses password for login portal => Phone & SMS are inferior to any other form.
6. Hardware 2FA is in the form of the credit card's chip (my other bank) => Hardware 2FA is inferior to Software 2FA.

I agree with you that there needs to be some ranking capability but not by ranking each 2FA option. At least not with the limited amount of data that we currently collect as the error rate would be too high.

I've worked with this since 2014 and I've seen so many different types of 2FA implementations/solutions that I can confidently say that ranking email, sms, phone, software & hardware is impossible and would be very unfair to the different providers out there.

@phallobst mentioned in some other PR/issue here today that a ranking system have been talked about in the last couple of months. One that mimics ssl labs' A-F system where a group of available implementations could be used to give a score.
I think that's a better solution that this one that you're suggesting here.

Regarding the mobile view: It's a non issue for me but sure 🤷‍♂ we can make it the same as the desktop one. On my [test site](https://2fa.carlgo11.com/) I simply do it by the order it's in the YAML file.

**Comment by leggomyinfo** [comment]
Since you see serious downsides and swapping hardware & software on desktop is at best a minor improvement, I think it probably makes sense to leave the desktop order as is for now. You seem to have put much more thought into this than I have, so I trust your take more than my own.

Let's still change the mobile order to match that of desktop though.

Also, +1 for an A-F system.

**Comment by Carlgo11** [comment]
Closing as the order is now the same on all devices
