### ISSUE TITLE
Add tickspot.com

### ISSUE THREAD

**Issue by JaneX8** [2factorauth/twofactorauth#4725]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that does not support 2FA: ###

* Site name - `Tick`

* Site URL - `https://www.tickspot.com`

* Does the site support 2FA? - `No`

### Information about the site's contact information: ###

* Site language - `English`

* Twitter username - `@tickspot`

* Facebook link - ``

* Email address - `support@tickspot.com`

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

**Comment by jamcat22** [comment]
Hi @ElleshaHackett!

It appears that the site you're requesting to be added does not support 2FA. I've modified your issue content to use our [template for sites that do not support 2FA](https://github.com/2factorauth/twofactorauth/issues/new?assignees=&labels=add+site&template=2-add-site-without-2fa.md&title=Add+%5Bsite+name%5D), rather than [the one for sites that currently support 2FA](https://github.com/2factorauth/twofactorauth/issues/new?assignees=&labels=add+site&template=1-add-site-with-2fa.md&title=Add+%5Bsite+name%5D).

I realize that the names on the [new issue page](https://github.com/2factorauth/twofactorauth/issues/new/choose) look similar, so I'll see if we can update the templates to be more clear in the future. 😄

We rely on pull requests (PRs) to help get code into our website efficiently. The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md). If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you'd rather not make a PR, that's totally fine. At some point, a contributor will take the content of your issue and make an associated PR so that the entry gets added to the site.

Thanks,
Jacob
