### ISSUE TITLE
Criteria

### ISSUE THREAD

**Issue by jamcat22** [2factorauth/twofactorauth#540]
I'm a little confused on the whole criteria of the site (https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md).

Why shouldn't this website show all websites you can enable 2fa on? Maybe not apps that are not in the cloud (like 1Password), but why not all cloud apps and websites?

**Comment by mxxcon** [comment]
@jamcat22 see  #394

**Comment by jdavis** [comment]
Because then literally every single site that requires you to login could be added. I can just scroll through my list of logins (384 sites) within 1Password and see a ton of sites that don't need 2FA.
- Meetup.com doesn't need 2FA
- MLB.com doesn't need 2FA (sorry fantasy baseball lovers)
- About.me doesn't need 2FA
- and the list goes on and on

The line needs to be drawn somewhere. If there wasn't a line, we might as well link to Google's search and say, here's the list of sites that should have 2FA.

**Comment by jamcat22** [comment]
Sorry to keep commenting on this, but while I understand the criteria for sites that do not support 2FA , I do not agree that it should apply to sites that support 2FA. It seems like the main purpose of this website would be to help people make their accounts more secure and show people what sites do not have the security features they should. If a site has 2FA, why should it be excluded from a list designed to show what sites support 2FA?

**Comment by jdavis** [comment]
@jamcat22 Have we blocked any sites that already have 2FA from being listed on the site?

Besides SAML and SSO sites, I don't recall shooting down any issues/PRs that add sites that already have 2FA.

However, I will block sites that don't match the criteria from being listed, like what was done in #391.

**Comment by smholloway** [comment]
I think we have to draw the line somewhere and @jdavis has done a great job setting that boundary. Why do we have to draw the line? Because there are hundreds of millions of websites. Of those, most people only visit a few per day. There's no way to provide a good user experience for a site that lists hundreds of millions of websites, especially when a user is only interested in a handful of them.
