### ISSUE TITLE
Distinguish between SMS and TOTP

### ISSUE THREAD

**Issue by jpgoldberg** [2factorauth/twofactorauth#595]
Currently systems that use TOTP (Time-based One Time Passwords) are categorized as SMS. SMS and TOTP systems actually have very different security properties. In particular, SMS messages can be intercepted; TOTP does not involve sending messages (other than at original enrollment.) The also have some major differences in availability.

From a user's point of view this may appear very similar, but they are in fact quite different. I've actually written up a description of TOTP here: http://blog.agilebits.com/2012/12/20/doing-the-two-step-until-the-end-of-time/ which might clarify the difference.

There may be good reasons to not present an overly complicated picture to users of your site. And so you may wish to keep "check a code on your phone" systems in one category for presentational purposes, conflating SMS and TOTP. But you may also wish to at least distinguish between these systems in your underlying data store. This way, you will be able to more easily make the distinction visible if you chose to at some later point.

**Comment by smholloway** [comment]
SMS refers only to the delivery mechanism. A provider could send a TOTP, HOTP, a secret word, a security question, or anything else. Also, SMS does not imply in-band or out-of-band; some SMS systems require the user to input a code on the website (e.g., "Your verification code is 591032. Enter it when prompted"), while others ask the user to reply via SMS (e.g., "Reply with the word FANTASTIC").

**Comment by jpgoldberg** [comment]
I'm sorry @smholloway, but I don't think you understand how TOPT and HOTP work. With [TH]OTP _the provider does **not** send any message_. No message is transmitted to the phone. No message is received by the phone.

**Comment by mxxcon** [comment]
@jpgoldberg if no messages are sent or received where does SMS come into play?

**Comment by jpgoldberg** [comment]
[Grr, I accidentally deleted my earlier post of this comment, thinking it got duplicated. Sorry for the repetition.]

@mxxcon With TOTP no messages are sent. But currently the site is listing such systems under "SMS". For example Dropbox uses TOTP. Anything that uses Google Authenticator is using TOTP, and these appear to be listed as "SMS" here.

### Appearances are deceptive

To most users (and also to many people here) TOTP will _appear as if_ it is a phone receiving a message with a code. People open a special app on their phone to see the one-time password (a six or eight digit number). The code changes every 30 seconds, and they need to enter it into the website within that 30 second window.

Thus it appears as if the site is sending a code to the phone and checking for a match. However, that is not at all what is happening. If you follow the link in my initial description of the issue, you will learn how this magic is done.

The device that a person uses does not need to have any kind of network/telephony connection at all to work. All it needs is an accurate clock. Phones are useful for this because they get the time from cellular stations, and their internal clocks will be accurate enough as long as they get a time update every couple of weeks.

### Appearances are important

As I've noted, most people using something like Google Authenticator on their phones will be under
the impression that the code is being sent from the server. And so for most people, categorizing TOTP with SMS will be most natural.

So if the the twofactor.org site were to present the "SMS" and "TOTP" separately, then it might end up causing more confusion then spreading clarity. So I could see opting to continue to present things like Dropbox under an "SMS" umbrella. But never-the-less, I think that this ticket should be re-opened so that at least the underlying data makes the distinction.

**Comment by mxxcon** [comment]
@jpgoldberg, I think once again we have some significant misunderstanding going on...

`SMS` column shows which entries use SMS for communicating 2nd factor for authentication. It doesn't matter what specific method is used _inside_ of that SMS message.
For sample:
Basecamp. As you can read here https://basecamp.com/help/guides/you/phone-verification it uses SMS to send you a verification code. This is the only way they support 2fa.
Alternatively look at https://wiki.joyent.com/wiki/display/jpc2/Improving+Security+Using+Two-Factor+Authentication+%282FA%29 Their only supported method is `software implementation` using Google Authenticator-compatible TOTP.

Taking your example of Dropbox, as can be seen here https://www.dropbox.com/help/363/en it supports BOTH sending 2nd factor over SMS _OR_ using Google Authenticator-compatible TOTP.

`SMS` column is used to show users that in order to use 2fa for a given entry they must have an ability to send or receive SMS messages. 
`Software Implementation` is the opposite of that. It shows that 2fa for a given entry is based around some sort of application running on their device. This is relevant for users that have phone without SMS messaging or users without phones.

**Comment by jpgoldberg** [comment]
> Taking your example of Dropbox, as can be seen here https://www.dropbox.com/help/363/en it supports BOTH sending 2nd factor over SMS OR using Google Authenticator-compatible TOTP.

Ah. I see.

> `Software Implementation` is the opposite of that. It shows that 2fa for a given entry is based around some sort of application running on their device. This is relevant for users that have phone without SMS messaging or users without phones.

Ah. Well in the words of Emily Latella, "Oh. that's different. Never mind."

Cheers,-j
