### ISSUE TITLE
Update Boursorama

### ISSUE THREAD

**Issue by Sami32** [2factorauth/twofactorauth#6060]
### Site name

Boursorama

### Site URL

https://www.boursorama.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

It support SMS, vocal call message and FIDO2/WebAuthn (Yubikey...):

https://www.boursorama.com/aide-en-ligne/mon-espace-client/identifiant-et-mot-de-passe/question/en-quoi-consiste-la-connexion-par-cle-de-securite-sur-internet-5165516

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by moviuro** [comment]
@Sami32 I have serious doubts about if Boursorama *truly* supports 2FA. Can you please confirm what happens when you:

1. login to your account through a private/incognito window
2. close all private/incognito windows
3. login to your account through a second private/incognito window

If you aren't asked for the 2FA code **twice**, then it's not 2FA.

I'm having very serious doubts because my own 2 banking accounts in France (HelloBank! and LCL) *don't* do it properly.

**Comment by Sami32** [comment]
No problem but i'll not have access to my FIDO2 keys before the end of this year so i hope that i'll not forgot this request until then ;)

AFAIK Boursorama is the only french bank supporting WebAuthn and perhaps one little private bank as well.

**Comment by moviuro** [comment]
Oh, have fun far away from your keys then. I'll ask around on other forums for other people to check then ;)
