### ISSUE TITLE
Need to add TeleSign to 2FA providers page

### ISSUE THREAD

**Issue by Irampunjabi** [2factorauth/twofactorauth#628]
TeleSign provides 2FA for several of the largest websites in the world (several of which are listed on your site as offering 2FA to customers).  They offer SMS, phone call and mobile app options and have been covered all over in the press recently:  

http://techcrunch.com/2014/07/03/authentication-provider-telesign-closes-round-at-49-million/

http://www.forbes.com/sites/jjcolao/2014/04/29/with-another-40-million-in-funding-telesign-looks-to-dominate-2-step-verification/

http://www.zdnet.com/telstra-invests-in-two-factor-authentication-company-7000031144/

They are leaders in their space and were actual visionaries in the field starting in 2005 and adding data intelligence to the authentication process as well.

**Comment by mxxcon** [comment]
@Irampunjabi less on marketing and more on substance. Whenever I see links to PR articles my eyes glaze over. We also don't need phrases like "visionaries in the field" either. I understand you are their sales lead, but you are not pitching a story to a news site here. There's no need to pretend that you are some altruistic 3rd party. Instead of "they" it's perfectly fine to say "we". Honesty looks much better.

It would be more helpful if you'd link to a good quality 32x32 logo image that we can use than link to press releases. :smiley:

**Comment by jdavis** [comment]
Feel free to open a new Pull Request with the changes for this to happen.

Until then, I'm closing this as I agree with @mxxcon in that the marketing is a bit too much; I don't want to encourage this by keeping it open for other Collaborators to see it and to make a pull request for it.

I feel that the work should either be done by someone using the service in a more organic/grass-roots fashion (like @zach-taylor originally did with Authy) or someone that works for the service.
