### ISSUE TITLE
Section icon appears under the section

### ISSUE THREAD

**Issue by mpdavis** [2factorauth/twofactorauth#9]
I'm not sure if this is by design or not, but it confused me at first.  Currently a sections icon appears after the section it relates to.

![](http://content.screencast.com/users/mikedavis.webfilings/folders/Jing/media/47d388f5-3729-4db7-a7d9-68447b7ac819/00000469.png)

If this is by design, just ignore this.

**Comment by jdavis** [comment]
Haha, yeah. It is by design but I'm thinking of consolidating it by removing it. I did have the section name above the actual table so the dividers separated things nicely, but now everything is pretty condensed.

Either we can change it to just a line or remove it all together.

I tried it with just a `<div class="ui divider"></div>` and it didn't look too badly.
